build/Scripts/Windows/Build.ps1, src/NuGet/SignTool.nuspec, src/SignTool/SignTool/Program.cs, src/SignTool/SignTool/SignTool.SignToolBase.cs, src/SignTool/SignTool/SignToolArgs.cs, src/SignTool/SignTool/project.json, src/SignTool/SignToolTests/SignTool.UnitTests.xunit.runner.json, src/SignTool/SignToolTests/SignToolTests.csproj
Removes -dotnetPath command line arg, since the microbuild real signing task won't be portable anytime soon.
=> SignTool: Use LocateVS to find msbuild when not specified

.gitignore, src/RepoToolset/Build.proj
Allows users to specify doing a full rebuild. This change is split into two commits, one for the gitignore and whitespace fixes, and one for the actual content change. Tagging @tmat for review.
=> Add rebuild support to repo toolset

src/RepoToolset/OptimizationData.targets
unless we write out a sentinel file the `ApplyOptimizations` task will never run.
=> adding PostCompileBinaryModification so the ApplyOptimizations task runs

src/RepoToolset/GenerateInternalsVisibleTo.targets
This ensures that the IVT files are included before the remaining code files which ensures that a program's entry point is never overwritten.
=> add auto-generated IVT file to F#'s CompileBefore collection

src/RepoToolset/XUnit.targets
FYI. @tmat 
Error was: dotnet exec needs a managed .dll or .exe extension. The application specified was '/home/tagoo/.nuget/packages/xunit.runner.console\2.3.0\tools\netcoreapp1.0\xunit.console.dll'
=> Updating _TestRunnerCommand so we don't get an error on Linux.

sdks/RepoToolset/tools/Tools.proj
The packages/index.json feed was deprecated a bit back, which is why we were getting failures restoring the feed tasks package in the orchestrated build.
=> Update package feed to new sleet feed

sdks/RepoToolset/tools/Build.proj, sdks/RepoToolset/tools/Sign.proj, src/SignTool/SignTool/BatchSignInput.cs, src/SignTool/SignTool/BatchSignUtil.cs, src/SignTool/SignTool/ContentUtil.cs, src/SignTool/SignTool/FileName.cs, src/SignTool/SignTool/JsonTypes.cs, src/SignTool/SignTool/OrchestratedBatchSignInput.cs, src/SignTool/SignTool/PathUtil.cs, src/SignTool/SignTool/Program.cs, src/SignTool/SignTool/SignToolArgs.cs, src/SignTool/SignTool/ZipData.cs
Not yet ready to merge but it's taken longer than I'd like to get something that works, so I'd like to get some feedback from @jaredpar and @tmat if possible.
Still need to test with a "real" build definition but this will require the supported functionality be turned on in a build of the Roslyn Repo Toolset.
How this is expected to work:
1) Run as normal but with argument -OrchestrationConfigFile **_Path to output file_**.  This will make a file similar to the existing SignToolData.Json but with some more info (theoretically enough to do the signing later).  For instance, running this on the symreader repo yields something like this:
```
{
"kind": "orchestration",
"sign": [
{
"certificate": "MicrosoftSHA1Win8WinBlue",
"strongName": "MsSharedLib72",
"values": [
{
"filePath": …
```
=> POC for Orchestratable SignTool

sdks/RepoToolset/RepoToolset.csproj, sdks/RepoToolset/tools/Directory.Build.props, sdks/RepoToolset/tools/Directory.Build.targets, sdks/RepoToolset/tools/RepoLayout.props
- Allow `ArtifactsDir` to be overridden.  This will let MSBuild build itself, and then use the built version of MSBuild to build itself again to
a different (stage 2) artifacts directory
- Add empty Directory.Build files in repo toolset targets folder.  This prevents Directory.Build.props and Directory.Build.targets being picked up when building Build.proj.
This allows you to set the `RepoToolsetDir` in another repo to a local repo for roslyn-tools to test out local changes.
- Show `.*proj` files (for example Build.proj) in solution explorer
=> Allow artifacts directory to be overridden

sdks/RepoToolset/tools/Version.props
FYI. @jaredpar, @jasonmalinowski, @tmat 
Port of https://github.com/dotnet/roslyn/pull/23999
=> Fixing the official build version to not longer go over 65535

sdks/RepoToolset/tools/Build.proj
Since we no longer import versions.props in build.proj ```$(UsingToolVSSDK)``` is not available. ```VisualStudio.Insertion.proj``` is a no-op for non-VSSDK repos anyways, so the condition was unnecessary.
=> Remove incorrect condition

sdks/RepoToolset/tools/GetBuildVersion.targets, sdks/RepoToolset/tools/VisualStudio.targets
The [Nerdbank.GitVersioning](https://github.com/AArnott/Nerdbank.GitVersioning) package defines a `GetBuildVersion` target: https://github.com/AArnott/Nerdbank.GitVersioning/blob/d398833fcdcb857fe44c3e8287f25b4058921181/src/Nerdbank.GitVersioning.NuGet/build/Nerdbank.GitVersioning.targets#L62
This conflicts with the `GetBuildVersion` target which repo toolset defines if `UsingToolVSSDK` is set to true.  The result is that if you try to enable the VS SDK in a project, then Nerdbank.GitVersioning will stop working.
This PR adds a workaround for this: you can set the `DefineGetBuildVersionTargetForVsix` to false to prevent repo toolset's version of this target from being defined.
I ran into this while [porting MSBuild to use repo toolset](https://github.com/Microsoft/msbuild/issues/2706). …
=> Make GetBuildVersion target optional to avoid conflict with Nerdbank.GitVersioning

sdks/RepoToolset/tools/Imports.targets, sdks/RepoToolset/tools/ProjectDefaults.props, sdks/RepoToolset/tools/RepositoryInfo.targets, sdks/RepoToolset/tools/SourceLink.targets, sdks/RepoToolset/tools/Workarounds.targets, src/BuildTasks/GenerateSourceLinkFile.cs, src/BuildTasks/MapSourceRoots.cs, src/BuildTasks/PathUtilities.cs
Implements SourceRoot handling as prototyped in https://github.com/tmat/repository-info.
See also https://github.com/tmat/repository-info/blob/master/docs/Readme.md.
=> Update SourceLink generating targets to new design

sdks/RepoToolset/tools/Localization.props, sdks/RepoToolset/tools/StrongName.targets
Use Satellite assembly generation task from Microsoft.NET.Sdk even when building with full Framework MSBuild.  This will support public signing, is deterministic, and always generates them as AnyCPU.
=> Use Roslyn instead of al.exe to generate satellite assemblies

sdks/RepoToolset/tools/PipeBuild.Publish.proj
Just a first pass doing nearly the simplest thing.
=> Updating PipeBuild.Publish to pass along manifest information.

sdks/RepoToolset/tools/StrongName.targets
There are projects which have dependent assemblies that are not signed, and this can break certain scenarios that expect that all signed binaries have signed dependencies.
=> Remove requirement that everything using repotools must be signed

src/GithubMergeTool/GithubMergeTool.cs
The merge tool looks for existing PRs for its merges and stops if it
finds any. However, the 'head user' specified by the GH API for listing
pull requests is not, in fact, the user name of the person who created
the PR, but the repo owner of the repo the branch was created on. The
code has been changed accordingly.
=> Stop GH merge bot from closing existing PRs

sdks/RepoToolset/tools/ProjectLayout.props, sdks/RepoToolset/tools/RepoLayout.props
Changes IntermediateOutputPath so that the `obj` directory of each project is shared between its Release and Debug builds. This allows NuGet to restore once and the generated NuGet files applied to both configurations.
Includes platform (x86, x64) in output paths.
=> Share obj directory between configurations

sdks/RepoToolset/tools/DefaultVersions.props, sdks/RepoToolset/tools/ProjectDefaults.props
Implement https://github.com/dotnet/designs/pull/33 in RepoToolset.
The package that's referenced pulls down only the reference assemblies for target frameworks that the project targets.
=> Add support for Reference Assemblies packages

sdks/RepoToolset/sdk/Sdk.targets, sdks/RepoToolset/tools/Build.proj, sdks/RepoToolset/tools/Empty.targets, src/BuildTasks/RoslynTools.BuildTasks.csproj, src/Directory.Build.props
Implements `ExcludeFromSourceBuild` property that projects can set to exclude themselves from source build.
=> Allow projects to opt-out of source build

sdks/RepoToolset/tools/Sign.proj, src/SignTool/SignTool/BatchSignUtil.cs, src/SignTool/SignTool/Program.cs
This will ensure that these get surfaced as MSBuild errors at any verbosity level.
https://blogs.msdn.microsoft.com/msbuild/2006/11/02/msbuild-visual-studio-aware-error-messages-and-message-formats/
=> Emit SignTool errors in canonical format

sdks/RepoToolset/tools/Build.proj, sdks/RepoToolset/tools/Compiler.props, sdks/RepoToolset/tools/DefaultVersions.props, sdks/RepoToolset/tools/Directory.Build.props, sdks/RepoToolset/tools/Directory.Build.targets, sdks/RepoToolset/tools/Settings.props
A few of fixes for source build and Linux build:
- Respect `DotNetRestoreSourcePropsPath` and `DotNetBuildOffline` source build variables
- Use `Microsoft.NETCore.Compilers` package when building via dotnet CLI on CI.
- Use `Microsoft.NET.Compilers` package when building via desktop msbuild on CI.
- Use locally installed compilers when building on dev machine.
=> Source Build fixes

src/SignTool/SignTool/Program.cs, src/SignTool/SignTool/SignTool.SignToolBase.cs, src/SignTool/SignTool/SignToolArgs.cs, src/SignTool/SignToolTests/SignTool.UnitTests.csproj
This is necessary with new signing to get diagnostic output about why
the signing is failing.
=> Option to have an MSBuild binary log emitted

src/SignTool/SignTool/SignTool.RealSignTool.cs
When using actual test signing then we shouldn't be validating the
signing of assemblies as it will fail (they're test signed).
=> Fix testsign validation

sdks/RepoToolset/tools/DefaultVersions.props
Update the version of XliffTasks used by the RepoToolset. Notably, this
new version inserts new `trans-unit` elements into .xlf files in sort
order rather than always putting them at the end. This should help
reduce merge conflicts when the .xlf files have changed in multiple
places.
=> Update XliffTasks version

sdks/RepoToolset/tools/VisualStudio.targets
Before the switch to sdks, `RepoToolsetDir` was supposed to be set by the repository. Now that repotoolset components are imported via sdk.props/targets, all paths should be local and self contained.
I tested that this works by modifying my local copy of repotoolset. Without the change it fails because `RepoToolsetDir` evaluates to empty string and it uses the current directory, not the project file directory as the base path for relative paths. With the change, the vsix magically appears :)
This is the only occurrence of `RepoToolsetDir`.
=> Replace RepoToolsetDir with MSBuildThisFileDirectory

src/BuildTasks/DownloadFile.cs
On a clean enlistment (such as in an official build), one of the first
things that happens is downloading the ProdCon version-override file. If
the destination directory (`artifacts/toolset`) doesn't exist, the overall
build will fail when DownloadFile's destination directory doesn't exist.
Create it instead. If it already exists, `Directory.CreateDirectory` does
not error so this should be safe.
=> Create destination directory in DownloadFile

src/CompilerPerfTests/run-perf.ps1
The "fetch dotnet" function was renamed from Ensure-SdkInPath to Ensure-DotnetSdk. This change reflects the rename.
=> Reflect a rename in the roslyn utils script

sdks/RepoToolset/tools/Imports.targets, sdks/RepoToolset/tools/Settings.props, sdks/RepoToolset/tools/Workarounds.targets
This adds an `ImportNetSdkFromRepoToolset` property which can be used to control whether the RoslynTools.RepoToolset Sdk imports Microsoft.NET.Sdk.  It defaults to true (so behavior is unchanged), but if you set it to false, you can use Microsoft.NET.Sdk (or Microsoft.NET.Sdk.Web) in your project files.  This means that new project templates will work without modification.
In order to do this, you can put the following in a Directory.Build.props file:
```xml
<PropertyGroup>
<ImportNetSdkFromRepoToolset>false</ImportNetSdkFromRepoToolset>
</PropertyGroup>
<Import Project="Sdk.props" Sdk="RoslynTools.RepoToolset" />
```
Similarly, you would put the following in Directory.Build.targets:
```xml
<Import Project="Sdk.targets" Sdk="RoslynTools.RepoToolset" />
```
Additionally, this PR removes …
=> Add property to control whether RoslynTools Sdk imports Microsoft.NET.Sdk

sdks/RepoToolset/tools/XUnit.targets
PR #192 broke running tests on mono (net461) on OSX.
Now:
- run netcoreapp tests on only Linux
- run !netcoreapp tests on all platforms
=> Run !netcoreapp tests on all platforms

src/SignTool/SignTool/BatchSignUtil.cs
Instead of the simple names.
This helps debugging if there's multiple files with the same simple name (e.g. satellite assemblies).
=> Print relative names in sign tool zip errors

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.Git.cs
When updating an existing PR the remote branch name sometimes starts with `refs/heads/` which needs to be removed.
=> sanitize the input branch name

src/RepoToolset/tools/BuildReleasePackages.targets, src/RepoToolset/tools/Imports.targets, src/RepoToolset/tools/Publish.proj, src/RepoToolset/tools/RepoLayout.props, src/RepoToolset/tools/SymStore.targets, src/RepoToolset/tools/Tests.props
Introduces the concept of *shipping artifacts*. 
By default project outputs are shipping, unless the project is a test project.
Project declares that its outputs are not shipping by setting property `<IsShipping>false</IsShipping>`.
The toolset sets the `PackageOutputPath` to `packages/Shipping` and `packages/NonShipping` directories, based on the value of `IsShipping`. 
All packages in `Shipping` directory and their content must be signed and symbols published to symbol server. 
All packages in `Shipping` directory will be published to NuGet.org. `NonShipping` packages will be published to MyGet.
=> Implement concept of shipping artifact

src/RepoToolset/tools/DefaultVersions.props
This version adds the required "signers" entry to the Willow manifest.
=> Update MicroBuild.Plugins.SwixBuild version to 1.0.422

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
Changes that just increase timeouts aren't great, but it sounds like this is the right option for now. This step often takes a bit longer than 10 minutes, and I have to sit there respinning over and over just hoping.
=> Allow 20 minutes for the VSTS DownloadArtifactsAsync instead of 10

src/RepoToolset/tools/VisualStudio.InsertionManifests.targets, src/RoslynInsertionTool/RoslynInsertionTool/Components.cs, src/RoslynInsertionTool/RoslynInsertionTool/CoreXT.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
This is to make other internal tooling better able to handle merge conflicts by adding a version for each inserted component.
The `.vsman` files used for insertion will be scanned for a `info/buildVersion` property which will be forwarded into a `version` property in the config JSON file.  See Microsoft/visualfsharp#5226.
=> add a `version` property to the inserted component

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/NLog.config, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.Designer.cs, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.settings, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs
The current behavior of this tool is to write a `rit.log` file in the current working directory.  This is annoying because our scheduled scripts do stuff like:
``` batch
RIT.exe /someoptions
copy rit.log rit.componentname.timestamp.log
```
This will enable a simple: `RIT.exe /someoptions /ll=rit.componentname.timestamp.log`.
I also got annoyed with updating all of the overloads in `RoslynInsertionToolOptions.cs` every time I add a new option so I followed the Roslyn pattern of `Optional<T>`.
=> enable the log location to be specified

.vsts-ci.yml
Add the branch name to the drop location.  This is important for internal scripts that find the most recent drop location.  As it stands the most recently completed build will be found regardless of the branch name, but with this change we can filter to `master` very easily.
=> add branch name to drop location

.vsts-ci.yml
With this change the `Publish Artifacts` build task now only takes 2 minutes instead of 15 (and it moves us off of a deprecated task.)
Compare the `Publish Artifacts` task for the internal build `20180718.2` (old) with `20180718.3` (this branch).
=> remove deprecated build task for one that's faster

eng/Versions.props
Having different versions causes loader issues such as https://github.com/dotnet/coreclr/issues/19357
=> Update dependencies to versions used by Arcade

src/SignTool/README.md, src/SignTool/SignTool/Program.cs, src/SignTool/SignTool/SignTool.SignToolBase.cs, src/SignTool/SignTool/SignToolArgs.cs
Make it easier to gather more detailed information when something is going wrong.
=> Add a `-diag` switch to sign tool to show more verbose output

src/VSIXExpInstaller/Program.cs
Resolve mscorlib satellite assembly before adding an `AssemblyResolve` handler to avoid a cycle resolving the assembly if an exception is thrown in the handler.
=> Resolve mscorlib resource assembly

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs
If an insertion has a DevDivInsertionFiles\DependentAssemblyVersions.csv file allow it to be used to update binding redirects
=> allow insertion tool to only update assemblt versions

src/GithubMergeTool/GithubMergeTool.cs
Some auto-created PRs are getting closed immediately, presumably because the backing branch is being deleted.  This is an attempt to report the status of the PR creation to try to debug why the branch is getting incorrectly deleted.
=> report PR creation failure

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
DDRIT tests were recently moved to a different auto-triggered build policy and the RPS one was renamed.  This will re-enable the RPS tests to be automatically queued.
=> update queued build policy name to reflect recent infrastructure changes

src/AzureFunctionPackage/Functions/Common/config.xml
Extra merge bot hop for introduction of 2.1.5xx in dotnet/sdk in between 2.1.4xx and 2.2.1xx.
cc @livarcocc @peterhuene
=> Update dotnet/sdk merges with 2.1.5xx

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
The regular queue's name got marked as `[deprecated]` which broke things. Trying to add the new queue while we're here.
=> Update RIT to kick off the correct RPS runs (both old & new) when insertions are created

src/RoslynInsertionTool/scripts/VS-Insertion.ps1
This does 3 things:
* Turn on insertions from `dev15.8` to `rel/d15.8`.  The latest build from `dev15.8` is already inserted into the `rel/d15.8` branch so **this will be a no-op**.  It's getting re-enabled here just to ensure that if there are any servicing fixes in the future they'll be automatically inserted.
* Move the `dev15.9` insertions to go to the preview branch `lab/d15.9stg`.  In the event we have a late-breaking fix for 15.9 we'll do manual insertions to `rel/d15.9` as necessary.
* Re-enable the insertion from `dev16.0` to `lab/ml` to conform (as much as possible) with the other insertions.
=> update F# insertions

src/AzureFunctionPackage/AzureFunctionPackage.csproj
With the migration to the Arcade build tools the shape of the artifacts directory changed which meant an empty Azure Function package was pushed, resulting in the deletion of the functions.
This PR updates the path to the expected shape and also adds an error if the expected functions were not present at zip file creation.  The `EnsurePackageSourceHasAllFunctions` target was first tested locally which resulted in the following error:
```
"D:\dotnet\roslyn-tools\src\AzureFunctionPackage\AzureFunctionPackage.csproj" (Restore;Build target) (1) ->
(EnsurePackageSourceHasAllFunctions target) ->
D:\dotnet\roslyn-tools\src\AzureFunctionPackage\AzureFunctionPackage.csproj(66,5): error : Azure Functions not found at 'D:\dotnet\roslyn-tools\artifacts\bin\AzureFunctionPackage\Debug\\package', check …
```
=> ensure all expected functions are in the package

src/SignTool/SignTool/SignTool.SignToolBase.cs
When signtool.exe is invoked in parallel on the same machine, there is contention for access to $AppBaseDir/build.proj. This moves the build.proj file into the intermediate output path instead to avoid this contention.
cc @jmarolf
=> Generate the build.proj file in the intermediate output path

src/RoslynInsertionTool/scripts/OneOffInsertion.ps1
Turns out that `switch` statement doesn't work like I thought and the `$ic` variable was always set to `"true"`.  This would lead to failed insertions when manually invoked (uncommon).
=> fix component insertion in script

.vsts-ci.yml
This cuts our official build time in half; we used to spend ~20 minutes copying files to the drop share, now it's down to ~10.
=> don't use deprecated drop task

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
This isn't necessary, I believe, because all the relevant data is stored in DependentAssemblyVersions.csv.
=> Remove ContractAssemblies.props copy step from insertion tool

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.Git.cs
If an invalid `VisualStudioBranchName` is supplied, the current error message is:
```
System.InvalidOperationException: Sequence contains no matching element
```
and that's not very actionable.  The new error message is:
```
System.ArgumentException: Visual Studio branch some-invalid-branch-name not found.
```
=> report an actionable error message

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.AssemblyVersions.cs
This was ultimately leading to a bunch of insertions failing because the format of the `DevDivInsertionFiles.csv` file sometimes looks like:
```
SomeAssembly, Version=1.2.3.4
```
and sometimes looks like:
```
SomeAssembly,1.2.3.4
```
=> version numbers don't always have the 'Version=' prefix

src/OptProf/roslyn.optprof.runsettings.generator.unittests/YamlTests.cs, src/OptProf/roslyn.optprof.runsettings.generator/Program.cs
This change allows for the branch specifier to live under the jobs node
in addition to the root of the YAML file.
=> Allow for branch under jobs node

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Pull information from the buildToInsert so that we can link to the last commit for this build.
Changes the PR description from `Updating {Options.InsertionName} to {buildVersion}` into `Updating {Options.InsertionName} to {buildVersion}. [({commitSHA})]({lastCommitUrl})`.
You can see an example on https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/158228?_a=overview
=> Update the PR description with a link to the last commit

src/RoslynInsertionTool/scripts/VS-Insertion.ps1
Disable Dev16.0 auto insertions as we're now in qb mode. 
Set master to flow to `vs/master` instead of via `vs/lab/ml`
=> Dev16 auto insertion updates

src/GithubMergeTool/GithubMergeTool.cs
The return value currently indicates that failing to create a PR because
there were no new commits is a failure, but it's actually a success
condition.
=> Change return value for CreateMergePrs

eng/Versions.props
Localization produces a lot of large resource assemblies that we don't need, and increases the time needed to download artifacts in deployment.
=> Disable localization for roslyn-tools

src/AzureFunctionPackage/Functions/Common/config.xml, src/AzureFunctionPackage/Functions/GitHubCreateMergePRs/run.csx
Frequent requests to fix merge conflicts or build warnings in merges to feature branches can be disruptive. Allow feature branches to opt-in to a weekly merge.
=> Support creating weekly github auto-merges

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
Adding three dots to the diff view gets you a much better overview of the changes.
See [this](https://github.com/dotnet/project-system/compare/63fa2f84..daf9606a?w=1) vs. [this](https://github.com/dotnet/project-system/compare/63fa2f84...daf9606a?w=1)
=> Add additional dot

src/RoslynInsertionTool/RoslynInsertionTool/ArcadeInsertionArtifacts.cs, src/RoslynInsertionTool/RoslynInsertionTool/InsertionArtifacts.cs, src/RoslynInsertionTool/RoslynInsertionTool/LegacyInsertionArtifacts.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Insert `.props` files from `VSSetup\Insertion\OptProf` directory to `{VS enlistment}\src\Tests\config\runsettings\Official\OptProf\External`.
These will be picked up by VS IBC training build.
=> Insert OptProf props files

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.AssemblyVersions.cs
This file is supposed to be optional yet we fail the insertion if it cannot be found
=> do not fail insertion if DependentAssemblyVersionsFile is not found

src/AzureFunctionPackage/Functions/Common/config.xml, src/RoslynInsertionTool/scripts/VS-Insertion.ps1
This updates the bot config to begin inserting and merging based off of `releases/dev16.1` and `releases/dev16.1-vs-deps` instead of `dev16.1` and `dev16.1-vs-deps`.
/cc @jaredpar @dpoeschl @JoeRobich
=> Update config for dev16.1->release/dev16.1 change

src/AzureFunctionPackage/Functions/Common/config.xml
Adding feature branch "owners" to the merge configuration so that Tigers can easily identify who to involve when Merge Conflicts or build failures seem inscrutable.
@agocke, @333fred Please take a look
=> Update Roslyn feature branch merge configuration with owners

src/AzureFunctionPackage/Functions/GitHubCreateMergePRs/run.csx
"The Search API has a custom rate limit. For requests using Basic Authentication, OAuth, or client ID and secret, you can make up to 30 requests per minute."
=> Add Delay to GitHub PR creation

src/RoslynInsertionTool/scripts/VS-Insertion.ps1
For 16.2 preview3, we will create insertions as needed
For 16.2 preview4, insertions will be created by https://devdiv.visualstudio.com/DevDiv/_releaseDefinition?definitionId=1837&_a=definition-pipeline
For 16.3, insertions will be created by https://devdiv.visualstudio.com/DevDiv/_releaseDefinition?definitionId=1838&_a=definition-pipeline
=> Move Roslyn to create insertion on successful signed build

src/RepoToolset/tools/Sign.proj
SignTool.exe takes the path to msbuild.exe as an argument. Currently, we
use vswhere.exe to locate an appropriate VS installation, then look for
msbuild.exe at a location relative to that. In VS 2017, this relative
path was "MSBuild\15.0\Bin\msbuild.exe", but in VS 2019 that has
switched to "MSBuild\Current\Bin\msbuild.exe". Here we update Sign.proj
to look for both, preferring "Current" but using "15.0" if that is all
that is available.
=> Look for MSBuild in more places

src/AzureFunctionPackage/Functions/GitHubAutoMergePRs/run.csx
Use `ex?.ToString()` instead to output the error.
=> Log.Error doesn't have an overload that takes an exception

src/AzureFunctionPackage/Functions/GitHubCreateMergePRs/run.csx
This is the first step in observing the type of rate-limiting that's being imposed by GH.
Next step: temporarily remove `Task.Delay()` so we can see whether GH is rate-limiting this script from an API standpoint or abuse, because that will dictate the type of fix necessary to remove the delay altogether.
=> log exceptions when creating merge PRs

src/GithubMergeTool/GithubMergeTool.cs
Reverts dotnet/roslyn-tools#540
Turns out the maestro bot doesn't support approving PRs yet, so we have to continue using our own for now.
=> Revert "Use the auto-merge label from arcade"

src/GithubMergeTool/GithubMergeTool.cs
Reverts dotnet/roslyn-tools#542
We're ready to try this again
=> Revert "Revert "Use the auto-merge label from arcade""

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
RPS isn't triggering on the insertion builds because of a policy name change that was made [here](https://devdiv.visualstudio.com/Engineering/_git/PullRequestBot/pullrequest/204633?_a=files). Updating our scripts to reflect the new name.
=> Updating the new RPS policy name

src/RoslynInsertionTool/RoslynInsertionTool/ArcadeInsertionArtifacts.cs
It looks like we don't use this folder structure any more in the VSSetup artifact. Updated the tool to match what we currently have.
This can save a little time on triggered pipelines which already need to download the artifacts for the build that they are triggered by.
=> Fix BuildDropPath for Arcade artifacts

src/RoslynInsertionTool/RoslynInsertionTool/CoreXT.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.AssemblyVersions.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/VersionsUpdater.cs
Closes #579 
Closes #572 (triggered builds must download artifacts, and now we download the Upload VSTS Drop logs more efficiently, so not really anything left to do here)
=> Various minor improvements

src/GithubMergeTool/GithubMergeTool.cs
Related to #621 
At the time we create the merge PR, we notice if there are conflicts and add an extra label if that is the case. /cc @dibarbet 
This handles some scenarios but not all. Some unhandled scenarios include:
1. The bot creates merges for master-to-master-vs-deps and 16.5-preview1-vs-deps to master-vs-deps. Once one is merged, we can start to have conflicts in the other merge.
2. The bot creates a merge for master-to-master-vs-deps. Then someone merges a PR to one of the branches which makes the bot PR start to have merge conflicts.
GitHub really should just show if a PR is known to have merge conflicts in the PR list just as it shows the checks results. But this is an inexpensive stopgap that gets us a lot of the triage improvements that we do want.
Example PR: …
=> Add extra label to PRs with merge conflicts

merge-pr-pipeline.yml
Trying to gauge thoughts on running merges every three hours instead of every 12.  
We specifically want to do this for Roslyn -vs-deps branches, but if an overall change to 3 works then we can do it this way rather than more difficult changes
Questions -
1.  Do we need to have different schedules for different repos?
2.  Should we only run on a more frequent schedule for specific branches?
If the answer to either 1 or 2 is Yes, then we'll need to make more invasive changes (e.g. multiple pipelines)
@jmarolf @dmonroym @brettfo @mavasani @JoeRobich for thoughts
=> Run the merge pipeline every 3 hours

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Fix to pick up latest builds that have partially succeeded as well with proper warnings. We dont anticipate this to happen unless there is a non-critical tooling problem like failing to index sources.
Addresses #666 .
=> Fix to insert partially successful builds

merge-pr-pipeline.yml, src/GitHubCreateMergePRs/Program.cs, src/GitHubCreateMergePRs/config.xml, src/GithubMergeTool/GithubMergeTool.cs
FYI @dibarbet @JoeRobich @RikkiGibson 
I was a little concerned about the case that it triggers a rebuild when existing run is almost finished, thus delay our codeflow. But looking at the time from PR creation to auto-merge in Roslyn, it usually happens in about 1.5 hours, well within the 3 hours window. So in most cases, we will only reset when CI failed or stuck (due to infra issue), which is actually desired.
Another change I'm considering is to rerun CI if it hasn't finished in certain time, which hopefully can mitigate some transient infra issue. Thoughts?
=> Add option to update an existing PR if it's already exist

src/GitHubCreateMergePRs/config.xml
Noticed in the CreateMergePR pipeline log that these branches no longer exist
```console
Merging roslyn from dev15.0.x to dev15.9.x
[error]Error creating PR. GH response code: NotFound
```
=> Remove Roslyn dev15.0.x branches from code flow

src/GitHubCreateMergePRs/config.xml
```console
Merging templates from dev16.3.x to master
##[error]Error creating PR. GH response code: NotFound
````
This seem right? @jmarolf
=> Remove dev16.3.x from Templates code flow

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RIT.csproj, src/RoslynInsertionTool/RoslynInsertionTool/CoreXT.cs, src/RoslynInsertionTool/RoslynInsertionTool/PackageInfo.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.Packages.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.csproj, src/RoslynInsertionTool/RoslynInsertionTool/SemanticVersion.cs
Reverts dotnet/roslyn-tools#722
Not all versions are semantic versions - https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-environment-logs&releaseId=593379&environmentId=3190919
=> Revert "Use NuGet.Versioning for SemanticVersion"

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Sometimes dev or feature branches have test insertions created. Instead of setting a PRnumber these insertions come from branch builds and can be identified by their prefix. These insertions should make the build queuer the reviewer.
=> When creating insertions for dev/ or features/ branches mark queuer as reviewer

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
The last insertion used 3581 of 4000 available characters. It feels like we could fit more information in the description.
BTW, this `http://github.com` -> `//github.com` change does not affect the way the link gets copied when you right click in the browser. You still get an https prefix so it shouldn't introduce problems in practice.
Baseline insertion: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/254613
Insertion with this change: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/254665
=> Use more of the available characters in the message limit

RoslynTools.sln, src/CreateTagsForVSRelease/CreateTagsForVSRelease.csproj, src/CreateTagsForVSRelease/Program.cs, src/CreateTagsForVSRelease/RoslynBuildInformation.cs, src/CreateTagsForVSRelease/VisualStudioVersion.cs
This tool walks the internal VS repo and sees what builds are tagged there, and then tags the matching builds in our repo.
=> Write a tool to tag commits that shipped in VS

.vsts-ci.yml
<strike>Borrowed the build yml from sourcelink (https://github.com/dotnet/sourcelink/blob/master/azure-pipelines.yml)</strike>
I stopped publishing to the drop path since that was causing the build to fail.
=> Stop publishing artifacts to drop path

src/GithubMergeTool/GithubMergeTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
/cc @JoeRobich 
The goal of this change is to make the preferred first-resort workflow easier to get going with :smile:
=> Add some helpful inline documentation

.vsts-ci.yml, NuGet.config, README.md, eng/Versions.props
We've been publishing to Azure Packages for a while. This completes the transition.
This PR does not update RepoTools project and all the embedded myget references within it.
=> Remove MyGet publishing

docs/RepoToolset.md, src/RepoToolset/tools/DefaultVersions.props, src/RepoToolset/tools/Tools.proj
- Change usages of dotnet-core feed to https://dotnetmygetlegacy.blob.core.windows.net/dotnet-core/index.json
- Change usages of roslyn feed to https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
- Change usages of roslyn-tools feed to https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json
- Change usage of other feeds under dotnet.myget.org to https://pkgs.dev.azure.com/dnceng/public/_packaging/myget-legacy/nuget/v3/index.json
PTAL @dmonroym @garath
=> Remove usages of dotnet.myget.org

src/GitHubCreateMergePRs/config.xml
16.10 branch is not needed since it is moved to master
=> Remove 16.10 branch

.vsts-ci.yml, README.md, docs/RepoToolset.md, merge-pr-pipeline.yml, src/AzureFunctionPackage/Functions/Common/VstsPrConfig.xml, src/GitHubCreateMergePRs/config.xml, src/RoslynInsertionTool/README.md, src/RoslynInsertionTool/RoslynInsertionTool/LegacyInsertionArtifacts.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs, src/SignTool/README.md
(Not quite ready to merge yet)
Switches occurrences of master to main and removes master from the yml pipeline. Some links to other dotnet repos will be broken, but since all dotnet repos are scheduled to switch over to main this sprint, this should be temporary.
`eng/common` files have been left purposely untouched since it appears modifying them may break things.
Some merge paths in config.xml are also left untouched since those repos have not made the switch yet from master-> main and I didn't want to break them.
=> Change occurrences of master to main

src/RoslynInsertionTool/RoslynInsertionTool/ArcadeInsertionArtifacts.cs, src/RoslynInsertionTool/RoslynInsertionTool/InsertionArtifacts.cs, src/RoslynInsertionTool/RoslynInsertionTool/LegacyInsertionArtifacts.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
As part of moving Roslyn's build, we will not have access to domain resources. We have been pulling copies of the component manifest when determining component version, but those same manifests are available from our insertion artifacts.
=> Read component version from local manifests when possible

src/GitHubCreateMergePRs/Program.cs, src/GitHubCreateMergePRs/config.xml, src/GithubMergeTool/GithubMergeTool.cs
example PR: RikkiGibson/roslyn#32
The expectation is that the repo-level 'mergeOwners' attribute is the username of the current tiger or similar. Merges that have a specific owner such as for a feature branch never notify the tiger when they are conflicts--they just notify the specific owner.
Someday it would be nice to automatically tag authors associated with conflicting changes. That will be more work though. Due to GitHub API limitations it might require local cloning and merging to enable us to identify and blame on conflicting regions.
=> Tag PR owners when a newly created PR has merge conflicts

src/GitHubCreateMergePRs/config.xml
We only need to maintain the LTS vs-deps release branches and the current release branches.
=> Simplify Roslyn code flow

src/CreateTagsForVSRelease/Program.cs
For builds that are no longer available, lookup the commit sha embedded in the Roslyn package's nuspec file.
cc: @jasonmalinowski
=> Enhance Release Tagger to tag more releases.

src/GitHubCreateMergePRs/config.xml
Now release/dev17.0 is targeting preview 2, we should resume the codeflow from main.
@sharwell @JoeRobich @dibarbet
=> Resume dev17 codeflow

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/App.config, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.Designer.cs, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.settings, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.Git.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs
This allows RIT to query builds from an AzDO instance (`BuildConnection`) that is not the AzDO (`VSConnection`) the VS insertion will be created in. Specifying a separate connection is not necessary and by default the VSConnection will be used for both purposes. 
Updated option names and methods to better distinguish whether the VSConnection or the BuildConnection should be used.
=> Add ability to query builds from a separate AzDO instance

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Since the OptProf props filename is based on repo name, during Roslyn's transition from inserting from GH dotnet/roslyn to inserting from dnceng dotnet-roslyn, this will ensure that we look for the proper props filename.
=> Fix the optprof props filename for Roslyn dnceng builds

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs, src/RoslynInsertionTool/scripts/HelperFunctions.ps1, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1, src/RoslynInsertionTool/scripts/UpdateExistingPr.ps1
Add new command line argument for specifying a GitHub repo name for the component being inserted. This allows us to generate a commit log for components that live on GitHub but build from an AzDO mirror.
Adds simple support for generating a commit log for components that live and build from AzDO repos.
=> Generate commit log for AzDO repos

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/App.config, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.Designer.cs, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.settings, src/RoslynInsertionTool/RoslynInsertionTool/PackageInfo.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.Packages.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs, src/RoslynInsertionTool/scripts/HelperFunctions.ps1, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1
This is adding possiblity to skip some packages from upgrading in corext.
Before this change there was hardcoded package VS.Tools.Roslyn which was not updating.
This change is adding setting SkipCoreXTPackages which is the list of packages to be skipped. By default it contains VS.Tools.Roslyn.
=> Add SkipCoreXTPackages option

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.Git.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1
This allows people to specify suffixes like `[Skip-SymbolCheck]` which will automatically skip symbol checks on the insertion without cluttering up the title prefix.
insertion generated with this change: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/335632
insertion manually edited to have `[Skip-SymbolCheck]` suffix: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/335602
=> Add titleSuffix argument to insertion tool

src/VSIXExpInstaller/Program.cs
Avoids the need for workarounds in dotnet/roslyn.
=> Add paths to assemblies not in standard locations

src/RepoToolset/tools/DefaultVersions.props, src/RepoToolset/tools/Localization.targets
The package name was changed to start with a reserved name (https://github.com/dotnet/xliff-tasks/issues/412)
However, I don't fully understand the flow with the very old default version. However, Arcade will stop setting the `XliffTasksVersion` property with the next update as it moved to `MicrosoftDotNetXliffTasksVersion` and this old version might come into action so we should update the package.
Resolves #1058
=> Move from XliffTasks to Microsoft.DotNet.XliffTasks

src/VSIXExpInstaller/Program.cs
In VS 17.0 Preview 3 the path to the Microsoft.VisualStudio.Threading library has changed. Without the updated path the 15.8 version of this library is discovered.
=> Update Microsoft.VisualStudio.Threading resolution path

src/GitHubCreateMergePRs/config.xml
Fixes the following by changing target branch from `master` to `main` for dotnet/templates.
```
Merging templates from dev16.0.x to master
##[warning]Error creating PR. GH response code: NotFound
##[warning]{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#compare-two-commits"}
```
Fixes the following by removing the configuration for dotnet/testimpact as it has been archived.
```
Merging testimpact from dev16.7.x to master
##[warning]Error creating PR. GH response code: NotFound
##[warning]{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#compare-two-commits"}
Merging testimpact from master to feature/vnext
##[warning]Error creating PR. GH response code: NotFound
##[warning]{"message":"Not …
```
=> Fix missing branch warnings in codeflow config.xml

RoslynTools.sln, src/VSBranchInfo/AzDOConnection.cs, src/VSBranchInfo/Program.cs, src/VSBranchInfo/README.md, src/VSBranchInfo/VSBranchInfo.csproj
This is a tool I wrote and have been using to help with VS Mac insertions for a while, but yesterday I added some package info stuff to it, for nuget publishing, and figured it should probably graduate to a proper repository.
It shows info about the currently inserted Roslyn bits for Visual Studio branches.
Output looks like this:
Most of it was stolen from the CreateTagsForVSRelease tool in this repo anyway, so there is certainly room for improvements/amalgamation.
=> Create VSBranchInfo tool

eng/Versions.props, src/BuildTasks.Tests/RoslynTools.BuildTasks.UnitTests.csproj, src/CreateTagsForVSRelease/CreateTagsForVSRelease.csproj, src/VSBranchInfo/VSBranchInfo.csproj
Issue: https://devdiv.visualstudio.com/DevDiv/_componentGovernance/112189/alert/2974928?typeId=6256257
The root reason is many of the packages are referencing NetStandard.Library 1.6.0, which is referencing System.Net.Http 4.1.0
For example:
Updating the version of this package would resolve the problem.
For other packages, which the updated version still referencing NetStandard.Library 1.6.0, explicitly referencing System.Net.Http 4.3.4
=> Update the version to avoid restoring System.Net.Http

src/GithubMergeTool/GithubMergeTool.cs
As the discussion happens yesterday,
Example:
When someone wants checkout to merge/main-to-main-vs-deps, and some remote forks might also have a branch using the same name.
This will make things becomes strange.
=> Specify remote tracking branch

RoslynTools.sln, src/NugetDependencyFinder/NugetDependencyFinder.csproj, src/NugetDependencyFinder/Program.cs
A little app that goes through a folder of `.nupkg` files and tells you which dependencies of those packages need to be updated to as released version.
Sample output:
=> Create NugetDependencyFinder app

.vsts-ci.yml
This ensures that a build pool is specified for the "Publish to Build Asset Registry" job.
=> Define build pool at the stage level

src/GitHubCreateMergePRs/config.xml
Since the PRs that I wanted to ignore are merged now, we can re-enable the automerging.
- https://github.com/dotnet/project-system/pull/7692
- https://github.com/dotnet/project-system/pull/7691
=> Re-enable project system merges

src/RoslynInsertionTool/RoslynInsertionTool/ArcadeInsertionArtifacts.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
When helping the TestPlatform get started with RIT, it was an unnecessary requirement to create this empty folder.
=> Do not fail if the Insertion\OptProf folder does not exist

src/RoslynInsertionTool/RoslynInsertionTool/CoreXT.cs
Attempting to mitigate this issue:
https://dev.azure.com/dnceng/internal/_build/results?buildId=1473406&view=logs&j=7ae71e7c-d4fe-51ea-64cd-240849b77ab1&t=e2756d63-0606-58d5-0f0d-91c79a5ba922&l=75
```
##[error] System.NotSupportedException: Adding a new package is not supported until we also update for LegacyProjects.props
at Roslyn.Insertion.CoreXT.AddNewPackage(PackageInfo packageInfo)
at Roslyn.Insertion.RoslynInsertionTool.UpdatePackages(BuildVersion buildVersion, CoreXT coreXT, String packagesDir, ImmutableArray`1 packagesToBeIgnored, CancellationToken cancellationToken)
at Roslyn.Insertion.RoslynInsertionTool.<PerformInsertionAsync>d__13.MoveNext()
```
=> Change LegacyProjects.props throw to warning

src/RoslynInsertionTool/RoslynInsertionTool/CoreXT.cs
The Roslyn Insertion Tool already tries to update `PackageReference` items in files under src/ConfigData/Packages in the VS repo. However, it only looks at files within that directory, and does not examine files in subdirectories. This means it fails to find and update Packages/Wizard/Packages.props and Packages/ProjectSystem/Managed.props when inserting builds of dotnet/project-system.
The fix is to retrieve **all** items under src/ConfigData/Packages when building a mapping from the package name to the .props file with the corresponding `PackageReference`, not just the top-level items.
=> Recurse through Packages subdirectories

src/GitHubCreateMergePRs/config.xml
We've deleted release/dev17.1-vs-deps in Roslyn, so any merge PRs to/from the branch are unnecessary.
=> Delete release/dev17.1-vs-deps from merge PR flow

src/GitHubCreateMergePRs/config.xml
@RikkiGibson brought up a good point that main-vs-deps should probably flow into release/dev17.3, at least for now, since we don't know whether we'll still need the main-vs-deps branch once 17.3 starts shipping.
=> Flow main-vs-deps to release/dev17.3

.azure-ci.yaml, RoslynTools.sln, src/dotnet-roslyn/Commands/NuGetPrepareCommand.cs, src/dotnet-roslyn/Commands/NuGetPublishCommand.cs, src/dotnet-roslyn/Commands/PRFinderCommand.cs, src/dotnet-roslyn/Commands/RootRoslynCommand.cs, src/dotnet-roslyn/Microsoft.Roslyn.csproj, src/dotnet-roslyn/NuGet/NuGetPrepare.cs, src/dotnet-roslyn/NuGet/NuGetPublish.cs, src/dotnet-roslyn/PRFinder/PRFinder.cs, src/dotnet-roslyn/readme.md
For the benefit of Roslyn acquisition duties. These are ports of powershell scripts I've been using.
=> Added nuget-prepare and nuget-package subcommands to dotnet-roslyn

src/GithubMergeTool/GithubMergeTool.cs
Currently this hardcodes `dotnet/roslyn`.
=> Update the merge PR description to contain real repo owner and name

src/dotnet-roslyn-tools/PRFinder/PRFinder.cs
This message was useful for VS Mac insertions. Putting it back in debug logging only, means I can add `-v:d` to the command line, but it should not affect roslyn CI builds (i hope!)
=> Show "Changes from .. to .." message when debug logging

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
Avoid path too long errors by using a new guid as the folder name instead of the branch name.
Resolves https://github.com/dotnet/roslyn-tools/issues/1200
=> Download artifacts to a uniquely named temp directory

src/dotnet-roslyn-tools/NuGet/NuGetDependencyFinder.cs
Sample output for `roslyn-tools nuget-dependencies`:
```
Finding dependencies...
Dependencies found.
Dependencies where a release version is unavailable:
Microsoft.DiaSymReader, 1.4.0-beta2-21528-02
```
Sample output for `roslyn-tools nuget-dependencies -v diag`:
```
Finding dependencies...
Dependencies found.
Dependencies in this folder:
Microsoft.CodeAnalysis.Common, 4.1.0-3.final
Microsoft.CodeAnalysis.CSharp, 4.1.0-3.final
Microsoft.CodeAnalysis.CSharp.Scripting, 4.1.0-3.final
Microsoft.CodeAnalysis.CSharp.Workspaces, 4.1.0-3.final
Microsoft.CodeAnalysis.EditorFeatures.Text, 4.1.0-3.final
Microsoft.CodeAnalysis.Features, 4.1.0-3.final
Microsoft.CodeAnalysis.Scripting.Common, 4.1.0-3.final
Microsoft.CodeAnalysis.VisualBasic, 4.1.0-3.final
Microsoft.CodeAnalysis.VisualBasic.Workspaces, …
```
=> Group and sort NuGet Dependency results

src/GitHubCreateMergePRs/config.xml
The branch will no longer be needed once the feature gets merged to main.
=> Remove semantic snippets from merge list

src/RoslynInsertionTool/RoslynInsertionTool/CoreXT.cs
Fixes failure when generating insertions for servicing branches.
```
Using artifacts provided in BuildDropPath: D:\a\_work\1\VSSetup
##[error] Microsoft.VisualStudio.Services.Common.VssServiceException: TF401174: The item 'Directory.Packages.props' could not be found in the repository 'VS' at the version specified by '<Commit: 7e73b799c3e113339d4e2d2456d8b71c08b89ac5 >' (resolved to commit '7e73b799c3e113339d4e2d2456d8b71c08b89ac5')
at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
```
Failing insertion: https://dev.azure.com/dnceng/internal/_build/results?buildId=1811662&view=logs&j=7ae71e7c-d4fe-51ea-64cd-240849b77ab1&t=e2756d63-0606-58d5-0f0d-91c79a5ba922 (microsoft)
=> Handle exceptions when package props file is not present

src/GitHubCreateMergePRs/config.xml
17.1 is no longer supported so no need to manage auto-merges through it. Once we merge here let's also delete the branch on the Roslyn side and remove from PublishData.
cc @jasonmalinowski @JoeRobich
=> Remove 17.1 from Roslyn merge config

src/dotnet-roslyn-tools/NuGet/NuGetPrepare.cs, src/dotnet-roslyn-tools/NuGet/NuGetPublish.cs
Microsoft.Net.Compilers.Toolset is the one true Roslyn compilers package. Remove the older packages from publishing.
=> Remove deprecated compilers packages from nuget publishing.

src/dotnet-roslyn-tools/Commands/PRTaggerCommand.cs, src/dotnet-roslyn-tools/Commands/RootRoslynCommand.cs, src/dotnet-roslyn-tools/Extensions/HttpClientExtensions.cs, src/dotnet-roslyn-tools/Microsoft.RoslynTools.csproj, src/dotnet-roslyn-tools/PRFinder/PRFinder.cs, src/dotnet-roslyn-tools/PRTagger/PRTagger.cs
- Implements a PR tagger that creates an issue with the PRs that were inserted in a given VS build.
- Currently works with Roslyn and Razor but can likely be extended to other repos as well.
- After this is merged, we should be able to trigger runs automatically via AzDo pipelines.
=> Add VS insertion PR tagger

src/dotnet-roslyn-tools/Commands/PRTaggerCommand.cs, src/dotnet-roslyn-tools/PRFinder/PRFinder.cs, src/dotnet-roslyn-tools/PRTagger/PRTagger.cs
Forgot this in the original PR - we need to pass in the product repo path as an argument since we won't necessarily be in the correct directory when running the release pipeline.
=> [PR tagger] Add repo path parameter

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Roslyn had not configured a default channel for a newly snapped release branch and this would have caught the issue earlier.
=> RIT: Queue symbol check for draft insertion PRs

src/GitHubCreateMergePRs/config.xml
Remove so that we can (potentially) merge the feature for Preview 2. If we don't make it, we can put it back or manually do merges.
=> Remove main sync for convert to record

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Queuing a policy that doesn't exist throws and exception and keeps us from starting other necessary policies.
=> Try to queue MSBuildRetail on draft insertions

src/VSIXExpInstaller/Program.cs
This brings them in line with https://github.com/microsoft/vs-extension-testing/blob/7e123a38b0b5f52a233f449390e0346c4c598655/src/Microsoft.VisualStudio.VsixInstaller.Shared/Installer.cs#L41-L86
verified this work locally to fix the hang when launching integration tests.
=> Update assembly resolution paths used by VSIXExpInstaller

src/GitHubCreateMergePRs/config.xml
Disabling auto merges to release branch, all fixes will have to be a separate PR.
=> `F#`: Disable `main` -> `17.4` branches auto-merges

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
Writing out pullRequest.Description multiple times is noisy, let's try using the Title instead.
https://dev.azure.com/dnceng/internal/_build/results?buildId=2028927&view=logs&j=7ae71e7c-d4fe-51ea-64cd-240849b77ab1&t=e2756d63-0606-58d5-0f0d-91c79a5ba922
<details>
<summary>Long log</summary>
```md
- [Implement equality semantics for async tagger tags. (take2) (64895)](//github.com/dotnet/roslyn/pull/64895)
- [Only write out inVs properties when appropriate (64853)](//github.com/dotnet/roslyn/pull/64853)
- [Get binlog on constructor failure (64899)](//github.com/dotnet/roslyn/pull/64899)
- [Save the resx file after a button is added into the WinForm (64910)](//github.com/dotnet/roslyn/pull/64910)
- [Update NuGet version to run MSBuildWorkspace tests against .NET SDK …
```
=> Compact logs

src/dotnet-roslyn-tools/Commands/PRFinderCommand.cs, src/dotnet-roslyn-tools/PRFinder/Formatters/DefaultFormatter.cs, src/dotnet-roslyn-tools/PRFinder/Formatters/OmniSharpFormatter.cs, src/dotnet-roslyn-tools/PRFinder/Hosts/GitHub.cs, src/dotnet-roslyn-tools/PRFinder/IPRLogFormatter.cs, src/dotnet-roslyn-tools/PRFinder/PRFinder.cs, src/dotnet-roslyn-tools/PRTagger/PRTagger.cs
Using the default formatter (`roslyn-tools pr-finder -p {prev} -c {curr}`):
```markdown
- [Create 1.25.1 release with omnisharp-roslyn updated to 1.39.2 (5430)](https://github.com/OmniSharp/omnisharp-vscode/pull/5430)
- [Clear all strict mode violations in src & enforce strict mode (5407)](https://github.com/OmniSharp/omnisharp-vscode/pull/5407)
- [Update debugger to 1.25.1  (5415)](https://github.com/OmniSharp/omnisharp-vscode/pull/5415)
- [Add github action to merge master to feature branches (5414)](https://github.com/OmniSharp/omnisharp-vscode/pull/5414)
- [coreclr-debug nullability (5405)](https://github.com/OmniSharp/omnisharp-vscode/pull/5405)
```
Using the OmniSharp formatter (`roslyn-tools pr-finder -p {prev} -c {curr} --format o#`):
```markdown
* Create 1.25.1 release with …
```
=> Add output formatters to the PR Finder command.

src/dotnet-roslyn-tools/Products/Razor.cs
Razor went from `razor-tooling` -> `razor`. We should update the Razor file accordingly
=> Update Razor after name change

src/GitHubCreateMergePRs/config.xml
Follow up from https://github.com/dotnet/roslyn/pull/65373
=> Delete -vs-deps branches from code flow

src/GitHubCreateMergePRs/config.xml
pre-requisite: https://github.com/dotnet/roslyn/pull/65990
=> remove main-vs-deps from code flow

src/GitHubCreateMergePRs/config.xml
Daily merges check to see if they're running within +/- 5 minutes of 12am.  This fails when time changes and it runs at 1am instead.  TBD how to fix that, but for now configure these branches to merge on every run
=> Merge feature branches on every run.

src/dotnet-roslyn-tools/NuGet/NuGetPublish.cs
The following PR added a new NuPkg file to Roslyn that we need to start publishing.
https://github.com/dotnet/roslyn/pull/66206
=> Include new NuPkg file

src/dotnet-roslyn-tools/PRTagger/PRTagger.cs, src/dotnet-roslyn-tools/Utilities/AzDOConnection.cs
One of our access PATs was expired and improved logging would have found the problem more quickly
=> Improve PR tagger logging

src/GitHubCreateMergePRs/config.xml
I don't think we need to maintain the code flow from 17.6 to 17.6-vs-deps since 17.6 is in GA now.
=> Remove 17.6 branch

src/dotnet-roslyn-tools/Commands/NuGetPublishCommand.cs, src/dotnet-roslyn-tools/NuGet/NuGetPrepare.cs, src/dotnet-roslyn-tools/NuGet/NuGetPublish.cs
Adds a `--skip-duplicate` flag for publishing purposes, and fixes a location that `Toolset.Framework` was missed. If you're curious, yes these two things are related.
=> Skip duplicate

src/dotnet-roslyn-tools/CreateReleaseTags/CreateReleaseTags.cs
I'm guessing due to all of the repo moves, there are a couple of commits that can't be found in the Razor repo, and they were stopping us progressing through to tagging more recent, relevant versions.
=> Don't error out when failing to apply a tag

RoslynTools.sln, src/ProjectDependencies/BuildDependencyFinder.cs, src/ProjectDependencies/MainWindow.xaml
Found this made things much more useful :)
=> Make Version optional in the project dependency finder

src/GitHubCreateMergePRs/config.xml
Add merge configurations to vscode-csharp so that changes made to the release / prerelease branches automatically flow back into main.
We don't need to flow release -> prerelease because main will have the changes from release.  When we snap main again we'll merge main into prerelease (which will contain the release changes as well).
=> Add branch merge configuration for vscode-csharp

eng/Versions.props, src/ProjectDependencies/ProjectDependencies.csproj
See this error when building locally
> C:\Users\gel\roslyn-tools\src\ProjectDependencies\ProjectDependencies.csproj : error NU1103: Unable to find a stable package NuGet.ProjectModel with version (>= 6.4
.1) [C:\Users\gel\roslyn-tools\RoslynTools.sln]
C:\Users\gel\roslyn-tools\src\ProjectDependencies\ProjectDependencies.csproj : error NU1103:   - Found 302 version(s) in dotnet-tools [ Nearest version: 6.4.2-rc.1
] [C:\Users\gel\roslyn-tools\RoslynTools.sln]
=> Fix missing dependency version

src/GitHubCreateMergePRs/config.xml
Saw we were being [questioned about older servicing branches](https://github.com/dotnet/roslyn/pull/68650), so took a look at what was currently under support. Checked code flow and saw it could use updating.
=> Remove Roslyn branches that are no longer under support.

src/dotnet-roslyn-tools/PRTagger/PRTagger.cs
https://dev.azure.com/dnceng/internal/_build/results?buildId=2388416&view=logs&j=9d82d844-45a0-5d2e-bd4b-992528a7bed5&t=5cca82b3-8182-5619-1c3b-68ef1449fa53
VS-Typescript is not a GitHub repo, and the tagger returns -1 causing the pipeline to fail. So Skip the repo.
=> Skip non-github repo, not return -1

merge-pr-pipeline.yml
netcore 3.1.20 is too old, should retire.
Test run: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9321682&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9
=> Use 9.x sdk to run merge PR pipeline

insertion-pr-tagger.yml
PR tagger is broken https://dev.azure.com/dnceng/internal/_build/results?buildId=2422541&view=results
And update the runtime to 9.0 solving the issue.
Verified in https://dev.azure.com/dnceng/internal/_build/results?buildId=2422800&view=logs&j=9d82d844-45a0-5d2e-bd4b-992528a7bed5&t=5cca82b3-8182-5619-1c3b-68ef1449fa53
=> Use .NET 9.0 to run PR tagger

src/RoslynInsertionTool/RoslynInsertionTool/CoreXT.cs, src/RoslynInsertionTool/RoslynInsertionTool/Extensions.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.Packages.cs
This is in preparation for an upcoming VS change which is removing certain corext files from the repo. As part of that work we expect to also start using Microsoft.Net.Compilers.Toolset for the toolset instead of VS.Tools.Roslyn.
The particular Roslyn change which will copy Microsoft.Net.Compilers.Toolset to VSSetup/DevDivPackages in the official build I haven't gotten working yet. However I think we might still be able to use RIT to insert successfully without it. We can't adjust the specific code paths for updating the toolset until we get the new toolset shipping in that directory though.
Test inserting into branch with no default.config: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/543224
Compare with insertion into main: …
=> Gracefully handle absence of .corext/Configs/default.config

.vsts-ci.yml, insertion-pr-tagger.yml
Test run https://dev.azure.com/dnceng/internal/_build/results?buildId=2436117&view=results
Our old pipeline lives under DevDiv and is disabled.
To make 1ES work and other future work easier, I move it to dnceng.
PR contains a lot of meaningless test commits, I will squash them into one commit.
=> Move the official build pipeline to dnceng and appy 1ES template

eng/SymbolPublishingExclusionsFile.txt
Exclude the symbol publish for libTo2Git.so, following the instructions [here](https://github.com/dotnet/arcade/blob/main/Documentation/CorePackages/Publishing.md#can-we-exclude-symbols-from-publishing-to-symbols-server)
Fix https://github.com/dotnet/dnceng/issues/2958#issuecomment-2137692339
=> Exclude libTo2Git.so

eng/SymbolPublishingExclusionsFile.txt
Should fix this https://dev.azure.com/dnceng/internal/_build/results?buildId=2462920&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=c7a8693b-2f9c-5ea8-c909-cde9405ac2e1
=> Exclude other libgit symbols

src/dotnet-roslyn-tools/Commands/PRFinderCommand.cs, src/dotnet-roslyn-tools/PRFinder/Hosts/Azure.cs, src/dotnet-roslyn-tools/PRFinder/Hosts/GitHub.cs, src/dotnet-roslyn-tools/PRFinder/IRepositoryHost.cs, src/dotnet-roslyn-tools/PRFinder/PRFinder.cs, src/dotnet-roslyn-tools/PRTagger/PRTagger.cs
Use the [GH Api](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests) to fetch PR titles if the commit message isn't indicative of a user provided message
TODO: This is limited by IP to 60 requests per hour. I managed to exceed that fairly easily.
```diff
diff --git a/description.md b/description.md
index 740b4d1..ae2cfc9 100644
--- a/description.md
+++ b/description.md
@@ -1,52 +1,52 @@
[View Complete Diff of Changes](https://github.com/dotnet/roslyn/compare/dd3795a49875bef2728f01e0284406f33ea1e2e1...e5dc6c6e6afd5bd217309ee540a22e1d88489a52?w=1)
- [Snap 17.11 Preview 2 (73753)](https://github.com/dotnet/roslyn/pull/73753)
-- [Merge pull request 73729 from CyrusNajmabadi/taggerAllocs](https://github.com/dotnet/roslyn/pull/73729)
+- [Lower allocations in …
```
=> Improve PR Descriptions

merge-pr-pipeline.yml
- Warning NETSDK1174: The abbreviation of -p for --project is deprecated. Please use --project.
=> Use `--project` flag as the `-p` alias is deprecated.

src/GitHubCreateMergePRs/config.xml
This will merge 17.11 back to main, and will disable main -> 17.11, while we preparing 17.12/net9/F#9
=> Close down F# 17.11 branch

src/dotnet-roslyn-tools/Commands/PRFinderCommand.cs, src/dotnet-roslyn-tools/PRFinder/Formatters/ChangelogFormatter.cs, src/dotnet-roslyn-tools/PRFinder/PRFinder.cs
Example output 
```
[View Complete Diff of Changes](https://github.com/dotnet/roslyn/compare/4fc2462522d2d63b94625f94bc0eaa2b28595d3d...2077862a15f4b955a4c5d139b82cb47087919e55?w=1)
* Revert "Remove semantic model keep-alive code in completion (#73844)" (#74302) (PR: [#74302](https://github.com/dotnet/roslyn/pull/74302))
* Remove fallbacks (#74041) (PR: [#74041](https://github.com/dotnet/roslyn/pull/74041))
* Fix UseNullPropagationCodeFixProvider for parenthesized property access (PR: [#74316](https://github.com/dotnet/roslyn/pull/74316))
* Disable BuildWithNetFrameworkHostedCompiler (#74299) (PR: [#74299](https://github.com/dotnet/roslyn/pull/74299))
* Avoid using constants for large string literals (#74305) (PR: [#74305](https://github.com/dotnet/roslyn/pull/74305))
* Adjust lowering of …
```
=> Add a changelog format that makes it easier to add a changelog for VS Code

src/dotnet-roslyn-tools/.vscode/launch.json, src/dotnet-roslyn-tools/.vscode/tasks.json, src/dotnet-roslyn-tools/Commands/PRFinderCommand.cs, src/dotnet-roslyn-tools/PRFinder/Formatters/DefaultFormatter.cs, src/dotnet-roslyn-tools/PRFinder/Hosts/Azure.cs, src/dotnet-roslyn-tools/PRFinder/Hosts/GitHub.cs, src/dotnet-roslyn-tools/PRFinder/IPRLogFormatter.cs, src/dotnet-roslyn-tools/PRFinder/IRepositoryHost.cs, src/dotnet-roslyn-tools/PRFinder/PRFinder.cs, src/dotnet-roslyn-tools/PRTagger/PRTagger.cs
The PR Finder can now filter results based on changes to a specific relative path in the repo. Also, I cleaned up the verbiage where we were referring to refs as SHAs to make it more clear that branches and tags can also be passed as arguments.
Without path filter (3 results):
```
~/Source/roslyn-tools/src/dotnet-roslyn-tools [main ≡ +0 ~3 -0 !]> dotnet run pr-finder -s d7261529b43f4581fb47e8f4d3d9197095d44508 -e main
Restore complete (0.3s)
Microsoft.RoslynTools succeeded (0.2s) → /Users/joeyrobichaud/Source/roslyn-tools/artifacts/bin/Microsoft.RoslynTools/Debug/net9.0/Microsoft.RoslynTools.dll
Build succeeded in 0.9s
[View Complete Diff of Changes](https://github.com/dotnet/roslyn-tools/compare/d7261529b43f4581fb47e8f4d3d9197095d44508...main?w=1)
- [Add a changelog format that makes it …
```
=> Adds an option to the pr-finder command to filter by path.

src/GitHubCreateMergePRs/config.xml
=> Remove 17.4 from servicing

src/GitHubCreateMergePRs/config.xml
@RikkiGibson @akhera99 FYI, you have (accidentally?) changed F#'s flow in https://github.com/dotnet/roslyn-tools/pull/1449, this reverts it back.
Our flow is: 
1. Previous release (`17.12`) goes to `main`.
2. `main` goes to current release (`17.13`).
=> Revert 17.13 flow change for F#

src/dotnet-roslyn-tools/.vscode/launch.json, src/dotnet-roslyn-tools/Commands/CreateReleaseTagsCommand.cs, src/dotnet-roslyn-tools/CreateReleaseTags/AbstractReleaseTagger.cs, src/dotnet-roslyn-tools/CreateReleaseTags/BuildInformation.cs, src/dotnet-roslyn-tools/CreateReleaseTags/CreateReleaseTags.cs, src/dotnet-roslyn-tools/CreateReleaseTags/ReleaseInformation.cs, src/dotnet-roslyn-tools/CreateReleaseTags/SdkReleaseTagger.cs, src/dotnet-roslyn-tools/CreateReleaseTags/VsReleaseTagger.cs, src/dotnet-roslyn-tools/Logging/ConsoleLoggerExtensions.cs, src/dotnet-roslyn-tools/Logging/SimplerConsoleFormatter.cs, src/dotnet-roslyn-tools/Products/FSharp.cs, src/dotnet-roslyn-tools/Products/IProduct.cs, src/dotnet-roslyn-tools/Products/Razor.cs, src/dotnet-roslyn-tools/Products/Roslyn.cs, src/dotnet-roslyn-tools/Products/TypeScript.cs, src/dotnet-roslyn-tools/VS/VSBranchInfo.cs
Roslyn is already creating tags for VS and the C# extension. This adds tagging for SDK releases.
I have already run this and pushed tags for both Roslyn and Razor repos.
=> Update create-release-tags command to create tags for SDK releases

src/dotnet-roslyn-tools/PRFinder/Hosts/GitHub.cs
The Arcade inter-branch merge GH action creates merge commits with a differently formatted message (ex. `[automated] Merge branch 'prerelease' => 'main' (#8039)`)
Tested by generating PR list between Roslyn main and Roslyn release/dev18.0:
*Before*:
```md
[View Complete Diff of Changes](https://github.com/dotnet/roslyn/compare/main...release/dev18.0?w=1)
- [[automated] Merge branch 'main' => 'release/dev18.0' (77445)](https://github.com/dotnet/roslyn/pull/77445)
- [[automated] Merge branch 'main' => 'release/dev18.0' (77441)](https://github.com/dotnet/roslyn/pull/77441)
- [[automated] Merge branch 'main' => 'release/dev18.0' (77431)](https://github.com/dotnet/roslyn/pull/77431)
- [[automated] Merge branch 'main' => 'release/dev18.0' (77409)](https://github.com/dotnet/roslyn/pull/77409)
- …
```
=> Ignore GH Action code flow PRs in PRFinder.

src/dotnet-roslyn-tools/.vscode/launch.json, src/dotnet-roslyn-tools/PRFinder/Hosts/GitHub.cs
Noticed that we were not removing PR numbers when [fixing up the C# ext. CHANGELOG](https://github.com/dotnet/vscode-csharp/pull/8071). Leaving the PR number in allows GH to turn it into a link when the number is in the range to be valid.
BEFORE:
* React to NuGet package pruning warnings (#11496) (PR: [#11496](https://github.com/dotnet/razor/pull/11496))
* Add a couple of "stress tests" to the integration test project (#11481) (PR: [#11481](https://github.com/dotnet/razor/pull/11481))
* Fix a couple of options in the old options screen (#11486) (PR: [#11486](https://github.com/dotnet/razor/pull/11486))
* Don't use Directory.Exists to check if a path is relative (#11483) (PR: [#11483](https://github.com/dotnet/razor/pull/11483))
* Fix another IDE0040 violation (#11474) (PR: …
=> Update the GH squash commit RegEx to remove the PR number.

src/dotnet-roslyn-tools/NuGet/NuGetPrepare.cs, src/dotnet-roslyn-tools/NuGet/NuGetPublish.cs
Now that roslyn-analyzer packages are building out of the roslyn repo, we will need to publish them along with our other packages.
=> Add roslyn-analyzer packages to the `nuget` command

src/dotnet-roslyn-tools/PRTagger/PRTagger.cs
Reverts dotnet/roslyn-tools#1503
=> Revert "Fix the build pipeline used by the PRTagger command"
