dotnet/roslyn-tools

RoslynTools.sln, build/Signing/BatchSignData.json, src/DownloadRoslynVsixes/DownloadRoslynVsixes.csproj, src/DownloadRoslynVsixes/Program.cs, src/DownloadRoslynVsixes/project.json, src/NuGet/BuildNuGets.csx, src/NuGet/DownloadRoslynVsixes.nuspec
@tmat for review.  Adding a tool used for getting vsixes for integration test runs.
=> adding DownloadRoslynVsixes

build/Scripts/Windows/Build.ps1, src/NuGet/VSIXExpInstaller.nuspec, src/VSIXExpInstaller/VSIXExpInstaller/Program.cs, src/VSIXExpInstaller/VSIXExpInstaller/VSIXExpInstaller.csproj, src/VSIXExpInstaller/VSIXExpInstaller/project.json
=> Updating the VSIXExpInstaller to be more explicit and to validate what it is doing

build/Scripts/Windows/Build.ps1, src/ModifyVsixManifest/ModifyVsixManifest/Program.cs, src/ModifyVsixManifest/ModifyVsixManifest/project.json, src/NuGet/ModifyVsixManifest.nuspec
Update SHA256 hash of extension.vsixmanifest file that is stored in manifest.json of the VSIX being modified.
=> ModifyVsixManifest: Update hash in manifest.json

src/SignTool/README.md, src/SignTool/SignTool/Program.cs, src/SignTool/SignTool/SignTool.SignToolBase.cs, src/SignTool/SignTool/SignToolArgs.cs
Add the ability to produce test sign binaries by using the -testSign
option.
=> Ability to test sign

src/RepoToolset/OptimizationData.targets
Thought this variable existed somewhere.  Turns out I was wrong.
=> Actually creating PostCompileBinaryModificationSentinelFile variable

src/RepoToolset/RepoLayout.props
=> Updating repo-toolset to use the correct dotnet host name on non-windows

src/NuGet/RepoToolset.nuspec
FYI. @tmat, forgot to do this as part of the change yesterday.
=> Moving repo toolset to 1.0.0-alpha49

src/SignTool/README.md
Just some stuff I noticed while reading it.
=> Grammar and spelling corrections

src/NuGet/RepoToolset.nuspec, src/RepoToolset/Tests.props, src/RepoToolset/XUnit.targets
=> Various test fixes for repo toolset.

sdks/RepoToolset/tools/DefaultVersions.props
Contains a bunch of bug fixes.
=> Update feed tasks version

sdks/RepoToolset/tools/DefaultVersions.props, sdks/RepoToolset/tools/ProjectDefaults.props, sdks/RepoToolset/tools/Workarounds.targets
=> Update compilers to 2.7.0-beta2-62330-02

sdks/RepoToolset/tools/SourceLink.targets, src/Directory.Build.props
Temporarily override the version to be able to build a new toolset package.
=> Version workaround

sdks/RepoToolset/tools/DefaultVersions.props, sdks/RepoToolset/tools/PipeBuild.Publish.proj
=> Updating the .NET Build Feed task to 2.1.0-prerelease-02419-01

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.Designer.cs
This file was not updated in the previous PRs for some reason.
=> Updating settings.designer file

sdks/RepoToolset/tools/StrongName.targets
=> Updating RepoToolset to force public signing on non-windows

build/Versions.props
Sets algorithm used to calculate source file checksums stored in PDB to SHA256.
=> Update RepoToolset to 1.0.0-beta-62614-04

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.csproj
Added ability to trigger a release before creating an insertion PR so symbol archival requests are made.
Also updated everything to the latest packages.
=> Trigger a release to symbol archive.

sdks/RepoToolset/tools/Workarounds.targets, sdks/RepoToolset/tools/XUnit.targets
* Works with the current xunit release
* Works with fast up-to-date check in Visual Studio
=> Update the workaround for xunit/xunit#1651

docs/RepoToolset.md, sdks/RepoToolset/tools/Compiler.props, sdks/RepoToolset/tools/VisualStudio.props
- Added PrivateAssets="all" to development dependencies.
- Updated RepoToolset.md.
=> Added PrivateAssets="all" to development dependencies

eng/Versions.props, src/VSIXExpInstaller/VSIXExpInstaller.csproj
fixes https://github.com/dotnet/roslyn-tools/issues/200
=> Fix vsix installer deps

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
=> Report insertion error if latest successful build has already been inserted, but there are more recent unsuccessful builds

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
=> Update artifact name

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/VersionsUpdater.cs
Update the insertion tool to handle new values being added to versions.xml and AssemblyVersions.tt.
I ran these changes locally and I can show you what the updated insertion looks like.
=> Update insertion tool

sdks/RepoToolset/sdk/Sdk.props, sdks/RepoToolset/tools/Empty.targets
Fixes https://github.com/dotnet/roslyn-tools/issues/245
=> Add DefaultTargets

src/GithubMergeTool/GithubMergeTool.cs, src/GithubMergeTool/test.csx
If a pull request is marked with the label "Auto-Merge If Tests Pass"
and this bot is enabled on the repo, the bot will automatically approve
and merge PRs when all merge requirements are satisfied.
=> Add automerge bot

sdks/RepoToolset/tools/AfterSigning.proj, sdks/RepoToolset/tools/AfterSolutionBuild.proj, sdks/RepoToolset/tools/Build.proj, sdks/RepoToolset/tools/BuildReleasePackages.targets, sdks/RepoToolset/tools/DefaultVersions.props, sdks/RepoToolset/tools/RepoLayout.props, sdks/RepoToolset/tools/Tools.proj, sdks/RepoToolset/tools/VisualStudio.InsertionManifests.targets
Convert VisualStudio.Insertion.proj to AfterSigning target.
Add NuGetRepack AfterSolutionBuild target.
=> Add Tools.props, AfterSolutionBuild.targets and AfterSigning.targets extensibility points.

src/GithubMergeTool/GithubMergeTool.cs
Feature branches currently have a special rule that treats any
test failure as a blocker. This is because many feature branches
don't have required tests, so otherwise all test failures would be
ignored. Rather than special casing feature branches, it's better
to recognize when there are no required branches and treat that
as the signifier instead
=> Replace special casing of feature branches

src/SignTool/SignTool/BatchSignUtil.cs
The post sign validation phase had very questionable value in the
SignTool. The intent was to verify assemblies were actually signed by
the sign process by calling into the CLR to verify their strong name
signature. That is flawed for a couple of reasons:
1. Strong naming is only part of the verification process hence the
verification is incomplete.
1. The exit code of signing actually tells us if signing succeeded or
not. Hence doing this validation is essentially not trusting the tooling
return code which is probably over paranoid.
Additionally this was causing problems when signing native binaries. To
the sign tool it's impossible to tell whether a.exe is a managed or
native binary. Strong name validation will always fail for a.exe even
when it is properly cert signed. Hence …
=> Remove post sign validation

src/AzureFunctionPackage/Functions/VstsCreateMergePRs/run.csx
run.csx(20,31): error CS0246: The type or namespace name 'Initializer' could not be found (are you missing a using directive or an assembly reference?)
=> Fixing error:

RoslynTools.sln, eng/SignToolData.json, src/OptProf/roslyn.optprof.lib/roslyn.optprof.lib.csproj, src/OptProf/roslyn.optprof.runsettings.generator/Constants.cs, src/OptProf/roslyn.optprof.runsettings.generator/Program.cs, src/OptProf/roslyn.optprof.runsettings.generator/roslyn.optprof.runsettings.generator.csproj, src/OptProf/roslyn.optprof.runsettings.generator/roslyn.optprof.runsettings.generator.nuspec
generates runsettings file for OptProf RPS runs
=> Runsettings generator

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Include the originating branch name & build number
=> Improve Insertion Titles

src/AzureFunctionPackage/Functions/VstsCreateMergePRs/VstsCreateMergePRs.csproj, src/AzureFunctionPackage/Functions/VstsCreateMergePRs/project.json, src/VstsMergeTool/VstsMergeTool.csproj
@brettfo 
I change the version of Nlog to 4.4.0
=> Change the version of Nlog to 4.4.0

src/AzureFunctionPackage/Functions/Common/config.xml
=> Include release/2.2.2xx to the CLI/SDK repo flows

src/RoslynInsertionTool/scripts/CreateDummyPr.ps1, src/RoslynInsertionTool/scripts/HelperFunctions.ps1, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1, src/RoslynInsertionTool/scripts/UpdateExistingPr.ps1
Also combine common functions.
=> pass more arguments to `UpdateExistingPr.ps1`

src/RoslynInsertionTool/scripts/HelperFunctions.ps1, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1, src/RoslynInsertionTool/scripts/UpdateExistingPr.ps1
This was divined from the current settings in VS-Insertion.ps1.
=> only auto-update assembly versions for Project System against non rel branches

src/RoslynInsertionTool/scripts/VS-Insertion.ps1
@brettfo I'm not sure about F# so I left it unchanged, so feel free to make change directly in this branch.
@jasonmalinowski @Pilchie @jinujoseph @ManishJayaswal
=> Add Preview 2 insertions (dircetly into master)

.azure-ci.yaml, README.md
=> add azure ci control file

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
This will fix the issue where `OneOffInsertion.ps1` is unable to report the created PRs URL.
=> collect the created PR ID

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs, src/RoslynInsertionTool/scripts/CreateDummyPr.ps1, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1, src/RoslynInsertionTool/scripts/VS-Insertion.ps1
Allows some differentiation for insertion PRs.  Individual insertions will be able to specify their own value (or empty).  Auto-insertions are now prepended with "[Auto Insertion]".
Fixes #410.
=> add a prefix to an insertion PR's title

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.Git.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs, src/RoslynInsertionTool/scripts/UpdateExistingPr.ps1
Added in an ability to update an existing PR as a fix for #396. If one chooses to overwrite it would now be a flag one can specify with the update schematics.
Also fixed the possibility of resetting to a stale base branch with a Fetch.
This might need a change to certain Release definitions - if someone can point me to these I'll go fix them up as well.
=> Update Existing PR

src/RoslynInsertionTool/scripts/VS-Insertion.ps1
For LUT and VSUT:
- Remove stale insertions
- Add Preview 2 insertions
=> Fix insertions for LUT and VSUT

src/AzureFunctionPackage/Functions/Common/VstsPrConfig.xml, src/AzureFunctionPackage/Functions/VstsCreateMergePRs/run.csx, src/RoslynInsertionTool/scripts/VS-Insertion.ps1
Also fixed the vsts insertion script.
=> VsUnitTesting branching for P2

src/AzureFunctionPackage/Functions/Common/config.xml
=> New branch merges to account for the 2 Dev16 releases of CLI/SDK

src/GithubMergeTool/GithubMergeTool.cs
@brettfo @jaredpar Is there an easy way to run this locally? I tried the api requests in postman and everything "should" be ok.
=> Add support for verifying GitHub Checks pass

src/AzureFunctionPackage/Functions/Common/config.xml
@livarcocc @nguerrera @dsplaisted
=> Add `release/3.0.1xx` branch for CLI and SDK repos.

src/RoslynInsertionTool/RoslynInsertionTool/Components.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
This will post a link to the diff of the changes being inserted vs what is currently inserted
=> post link to insertion diff

src/AzureFunctionPackage/Functions/Common/config.xml
This reverts commit 43a5b8a9401ec5dd756a46d670c0e72740bdb2e4.
=> Revert "Update config.xml"

src/AzureFunctionPackage/Functions/Common/config.xml, src/RoslynInsertionTool/scripts/VS-Insertion.ps1
- Add dev16.1-preview1 branches to auto-merging
- Add 16.1 preview1 insertion
- fix some whitespace just because
=> Update merges and insertions for 16.1 preview 1

src/RoslynInsertionTool/scripts/VS-Insertion.ps1
This finishes the snap and makes us start inserting Roslyn master into VS 16.1-preview3.
=> Update VS insertion config for 16.1-p2 snap

src/AzureFunctionPackage/Functions/Common/config.xml
@jasonmalinowski for merging permissions.
=> lock down F# dev16.1 branch flow

src/OptProf/roslyn.optprof.runsettings.generator/Constants.cs
@tmat @jaredpar @dotnet/roslyn-infrastructure
=> Add ShutdownCommand for VBCSCompiler

src/RoslynInsertionTool/scripts/VS-Insertion.ps1
Due to the snap this afternoon.
/cc @chsienki @dpoeschl @JoeRobich
=> Insert 16.2-p2 into lab/d16.2stg instead of master

src/AzureFunctionPackage/Functions/Common/config.xml
=> Don't flow 16.1-vs-deps changes downstream

src/AzureFunctionPackage/Functions/Common/config.xml
related to dotnet core snap. /cc @agocke @JoeRobich
=> Prevent flowing master changes into 16.3-p1

src/AzureFunctionPackage/Functions/Common/config.xml
=> Update auto-merge config for snap

src/AzureFunctionPackage/Functions/GitHubAutoMergePRs/run.csx
Add try/catch around attempted merges and log failures.
=> Handle exceptions on attempted merges

src/AzureFunctionPackage/Functions/Common/config.xml
=> Add features/ide-cleanup to automerge config

src/AzureFunctionPackage/Functions/Common/config.xml
master is taking over, so the merges should go the other way until we can delete the branch
=> Invert the merge flow for dev16.4-preview1

src/AzureFunctionPackage/Functions/Common/config.xml
flow master into 16.5 p1 branch.  I didn't create vs-deps yet as there isn't a VS branch for it yet... let me know if I should.
=> Flow master into 16.5 p1 branch.

src/AzureFunctionPackage/Functions/VstsCreateMergePRs/function.json
Pushing an update to disable the function before removing the publishing step.
=> Disable VSTS function.

.vsts-ci.yml, merge-pr-pipeline.yml
2 items
1.  Remove azure publishing steps.
2.  Fix the scheduled pipeline to not run on every commit.
=> Remove azure

RoslynTools.sln, src/RoslynInsertionTool/PRFinder/PRFinder.csproj, src/RoslynInsertionTool/PRFinder/Program.cs
/cc @dibarbet @JoeRobich 
this version of it also will fetch and retry if it couldn't find the specified commits (likely, when the commit being inserted was a very recent merge commit to master-vs-deps)
=> Add PRFinder to RoslynTools

src/GitHubCreateMergePRs/config.xml
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3168484 failed.  Maybe we should add running a dryrun to CI?  Could add a trigger that sets the dry run var to true.
`dotnet run --project .\src\GitHubCreateMergePRs\GitHubCreateMergePRs.csproj` to do a dryrun
=> Add missing equals in xml

merge-pr-pipeline.yml, src/GitHubCreateMergePRs/Program.cs
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3168734
TODO - figure out how to handle secrets from PRs from forks.
=> Trigger dryrun on PR

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
This changes some error messages to make it more obvious what developers need to do to run the tool locally.
=> Improve errors for local runs

src/GitHubCreateMergePRs/config.xml
Draft - branches are not created yet.
=> Snap for 16.4 P3

global.json, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
=> Fix change log

src/GitHubCreateMergePRs/config.xml
@rainersigwald @livarcocc @mmitche
Moving to maestro with https://github.com/dotnet/versions/pull/521
=> Remove CLI repos, moving to maestro merge bot

src/RoslynInsertionTool/RoslynInsertionTool/CoreXT.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/VersionsUpdater.cs
=> Fix XML formatting

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
* Ignores msftbot commits
* Changes #PrNumber to just PrNumber to avoid AzDO linkification
* Get a more descriptive commit message for Merge Commits
Compare the commit messages for https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/211363 (before) with https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/211391 (after)
=> Use better messages for Merge PRs

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
This wasn't working as expected after my recent changes, so fixing now. FYI @shyamnamboodiripad
=> Fix UpdateExistingPr

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RIT.csproj, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
=> Give a special message when there are no new commits

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Closes #587 
Also makes the behavior around failing to get the old build a little more graceful. ~~When the old build is not from the same branch we fail to look it up. This can be fixed, just want to do it separately.~~ Ended up just doing it, the REST API to get builds has a buildNumber parameter so it's pretty simple.
=> UpdateExistingPr should get file versions from PR branch

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.AssemblyVersions.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/VersionsUpdater.cs
/cc @tmat
related to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1011582
=> Don't update Stub.exe.config or versions.xml

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
=> Use a better heuristic to filter out PRs in the insertion log

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
This enables us to use the Pull Requests widget in AzDO dashboards.
=> Auto-add mlinfraswat as a reviewer

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
Before: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/219112
After: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/219205
Fixes #628
=> Support Squash Merges with mulit-line messages

src/GitHubCreateMergePRs/config.xml
Won't merge until snap and branches are created
=> Update roslyn branch flow for 16.5 P2

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
Now that we want to encourage more one off insertions from PRs. We should include those commit messages in the Insertion description. This PR adds commit messages to the description until it encounters the first Merge PR.
Fixes #684 
Updating Roslyn from [20200131.1](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_build/results?buildId=3430978) ([1ea3f65](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_apis/build/builds/3430978/sources)) to [20200203.2](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_build/results?buildId=3438098) ([d1dea11](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_apis/build/builds/3438098/sources))
---
[View Complete Diff of …
=> Update Insertion PR description with commits since last PR

merge-pr-pipeline.yml
Reverts dotnet/roslyn-tools#688
=> Revert "Update sdk version used in merge pipeline"

merge-pr-pipeline.yml, src/GithubMergeTool/GithubMergeTool.cs
So we can use 3.0 tools while targeting 2.1
@RikkiGibson
=> Fix yaml to pick up SDK based on global.json

src/GithubMergeTool/GithubMergeTool.cs
=> Serialize anonymous objects for json body

src/RoslynInsertionTool/README.md, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs, src/RoslynInsertionTool/scripts/HelperFunctions.ps1, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1, src/RoslynInsertionTool/scripts/UpdateExistingPr.ps1
=> Enable autocomplete

src/GitHubCreateMergePRs/config.xml
We should come up with a plan for getting our service branches consistent.
=> Update Roslyn code flow configuration

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Instead of "RIT Auto-Complete" use messages like "Updating Roslyn from 20200224.1 (88dd6e5) to 20200224.2 (d51adc7)"
Fixes #708
=> Use PR description for merge commit message

src/GitHubCreateMergePRs/Program.cs
Fixes https://github.com/dotnet/roslyn-tools/issues/364
=> Add daily merge frequency to GHCreateMergePR

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
The URL will be displayed in insertion description if build has Tag `PRNumber:[PR number]`
=> Add link to PR for validation build

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.Git.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Use the AzDO Id of the user who queued the PR Validation build as the reviewer of the insertion.
=> Make PR Validation queuer the insertion reviewer

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Who hasn't forgotten to update an overwritten dummy PR's title before inserting?
=> Update insertion PR title when overwriting

src/GitHubCreateMergePRs/config.xml
- Delete features/patterns3 merge
- Add merge for features/target-typing
- Add merge for features/covariant-returns
=> Update GitHubCreateMergePRs/config.xml for recent language feature branch changes

src/GitHubCreateMergePRs/Program.cs, src/GithubMergeTool/GithubMergeTool.cs
Closes #758
Test PR: dotnet/roslyn#43935
=> Automatically assign merge "owners" to PRs

src/GithubMergeTool/GithubMergeTool.cs
=> Fix mergeable status check

src/GithubMergeTool/GithubMergeTool.cs
This might help us get to the bottom of why @333fred is not getting assigned to his feature branch merge PRs.
Example log:
```
Merging roslyn from master to master-vs-deps
Creating branch
Resetting branch merges/master-to-master-vs-deps
Creating PR
Waiting for mergeable status..
PR has merge conflicts. Adding Merge Conflicts label.
Adding assignees: RikkiGibson, INVALID
##vso[task.logissue type=warning]RikkiGibson/roslyn merges/master-to-master-vs-deps has invalid owner "INVALID".
Actual assignees: RikkiGibson
PR created successfully
```
=> Log assignees for debugging

src/GitHubCreateMergePRs/Program.cs
For a few days now we've had "successful" GitHub Create Merge PRs runs which have actually failed to create any PRs. Let's ensure that if any PR creation results in a "bad" error that we give an error exit code, ensuring that the pipeline run will show as failed.
I decided that HTTP 422 and HTTP 404 are not "bad" errors. They happen on a regular basis, especially 422 which occurs when (IIRC) we can't push more commits to the merge branch or things like that. 404 happens when config.xml references a branch which has been deleted from the repo
Here's an unhelpful run from master: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3789676&view=results
Test run of this change: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3789687&view=results
=> Give an error exit code if a bad error occurs when creating a PR

src/GitHubCreateMergePRs/config.xml
Add features/interpolated-string-constants, assigned to @kevinsun-dev and myself.
=> Update merge pipelines

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
Currently failing
https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-environment-logs&releaseId=727349&environmentId=3972420
=> Fix description length check

.vsts-ci.yml, eng/Signing.props, eng/Versions.props, src/BuildCleanupTool/BuildCleanupTool.csproj, src/BuildCleanupTool/Mono.Options/Options.cs, src/RepoToolset/tools/ProjectDefaults.props, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Mono.Options/Options.cs, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RIT.csproj
Test build showing publishing stages will run https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3917202&view=results
=> Add arcade publishing step

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs
Closes #800
See https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/264858?_a=commits for an example insertion
=> Add /cherrypick option

src/GitHubCreateMergePRs/config.xml
Looks like this went missing somewhen!
=> Update branch flow for 16.9

src/GitHubCreateMergePRs/config.xml
Related to https://github.com/dotnet/project-system/pull/6558
FYI @dmonroym
=> Update project-system to main

.vsts-ci.yml
Test Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4462497&view=results
=> Move to SetScale build pools.

src/GitHubCreateMergePRs/config.xml
Adds list pattern merges. @alrz is a non-MSFT contributor but will be doing the implementation here, so I'm adding him to be notified when the merge bot encounters errors. alrz, you won't be able to resolve these errors on your own, but I can work with you to make sure merges end up correct.
=> Add list patterns merges

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs
/cc @allisonchou 
Will try making a test insertion with this change if I get the chance.
=> Handle spaces in /cherrypick argument

src/GitHubCreateMergePRs/config.xml
=> roslyn sdk codeflow from main to dev17.0

src/RoslynInsertionTool/scripts/HelperFunctions.ps1, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1, src/RoslynInsertionTool/scripts/UpdateExistingPr.ps1
Updates the scripts to support the changes from https://github.com/dotnet/roslyn-tools/pull/912
=> Update insertion scripts with ability to specify separate build azdo instance

src/RoslynInsertionTool/scripts/HelperFunctions.ps1, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1, src/RoslynInsertionTool/scripts/UpdateExistingPr.ps1
Missed a parameter in https://github.com/dotnet/roslyn-tools/pull/942
=> Pass ComponentUserName when ComponentAzdoUri specified

eng/Versions.props, src/BuildCleanupTool/BuildCleanupTool.csproj, src/BuildRetainer/BuildRetainer.csproj
Fixing dependabot alerts and unifying dependencies
=> Upgrade System.Net.Http and cleanup other dependencies

src/GitHubCreateMergePRs/config.xml
=> Update project-system flow

src/GitHubCreateMergePRs/config.xml
I just have an offline discussion with @vatsalyaagrawal and we want to pause the change from 16.11 to 17.0 P1
=> Stop 16.11 to 17.0 P1

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
Test Insertion: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/330591 (Microsoft only)
=> Use the AzDO commit url instead of calling .ToString()

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Resolves https://github.com/dotnet/roslyn-tools/issues/979
@RikkiGibson
=> Build components list from vs manifests in artifacts

src/RoslynInsertionTool/README.md, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.Git.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs
You can now specify who you want to default as a reviewer in your PRs. This fixes #996 and should relieve the amount of noise MLInfraSwat was receiving.
=> Add option of reviewerGUID

src/CreateTagsForVSRelease/AzDOConnection.cs, src/CreateTagsForVSRelease/CreateTagsForVSRelease.csproj, src/CreateTagsForVSRelease/Program.cs
Also, supports locating Roslyn builds in dnceng
=> Generate Roslyn tags for dev17 releases

src/RoslynInsertionTool/RoslynInsertionTool/CoreXT.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
Resolves #1024 
PTAL @JoeRobich @dotnet/roslyn-infrastructure
=> Automatically update LegacyProjects.props

src/GithubMergeTool/GithubMergeTool.cs
Example PR: RikkiGibson/roslyn#51
This change should make it so that if optional checks fail on an auto-merge PR, we just go ahead and merge anyway.
=> Use GitHub auto merge API

src/GitHubCreateMergePRs/config.xml
=> Remove unused branches

NuGet.config, eng/Versions.props, src/VSIXExpInstaller/VSIXExpInstaller.csproj, src/VSIXExpInstaller/VSIXExpInstaller.nuspec
=> Update VSIXExpInstaller for dev17

src/GitHubCreateMergePRs/config.xml
Fixes roslyn codeflow for after snap
=> Update Roslyn codeflow

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
Not all manifests will contain insertable components. Log these situations but do not crash.
=> RIT: when reading components from manifests be tolerant of errors

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs
Instead of letting an exception be thrown when encountering a null value from a component manifest. Search the package payloads for a valid drop url.
=> RIT: search manifest packages for a valid payload

src/GitHubCreateMergePRs/config.xml
=> Change to daily

src/GithubMergeTool/GithubMergeTool.cs
Resolves https://github.com/dotnet/roslyn-tools/issues/1090
=> Check for unsynched commits before generating GH merge PR

src/GitHubCreateMergePRs/config.xml
Add merge from 17.1 -> 17.1-vs-deps
=> Add merge from 17.1 -> 17.1-vs-deps

.vsts-ci.yml
Test Build - https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5276875&view=results (microsoft)
=> Move to 1ES build pool

src/GitHubCreateMergePRs/config.xml
=> Update PR owner to new Tiger

src/RoslynInsertionTool/RoslynInsertionTool/CoreXT.cs
Ensuring we process the parent Packages.props file as well and pull in the props directories straight from there.
=> Updates to props file parsing in the insertion tool

src/GitHubCreateMergePRs/config.xml
For the newly created [dev17.2.x](https://github.com/dotnet/project-system/tree/dev17.2.x) branch.
=> [Project System] Add dev17.2.x -> main

.vsts-ci.yml
Test Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5782940&view=results (microsoft)
SBOM should be in build artifacts.
=> Add build step to generate SBOM

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs
It appears to be necessary to manually queue these now.
=> Queue more tests on draft PRs

src/GitHubCreateMergePRs/config.xml
=> Update merge PR owner

eng/AfterSolutionBuild.targets, eng/Signing.props, src/dotnet-roslyn/Commands/CreateReleaseTagsCommand.cs, src/dotnet-roslyn/Commands/RootRoslynCommand.cs, src/dotnet-roslyn/CreateReleaseTags/AzDOConnection.cs, src/dotnet-roslyn/CreateReleaseTags/CreateReleaseTags.cs, src/dotnet-roslyn/CreateReleaseTags/RoslynBuildInformation.cs, src/dotnet-roslyn/CreateReleaseTags/VisualStudioVersion.cs, src/dotnet-roslyn/Microsoft.Roslyn.csproj
TODO: Need to verify this packages correctly in our official build
=> Move CreateVSReleaseTags to be Roslyn tool subcommand

src/dotnet-roslyn/Commands/VSBranchInfoCommand.cs
=> Lowercase is best for command line

src/GitHubCreateMergePRs/config.xml
=> Update merge owner to new tiger

src/RoslynInsertionTool/scripts/HelperFunctions.ps1, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1
Pre-requisite for using the dotnet-bot service account
PR generated by this - https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/394836 (but using my account and PAT, need the actual variable groups to run with dotnet bot).
=> Support different usernames and tokens in one off insertion

src/dotnet-roslyn-tools/Authentication/Authenticator.cs, src/dotnet-roslyn-tools/Authentication/Constants.cs, src/dotnet-roslyn-tools/Authentication/EncodedFile.cs, src/dotnet-roslyn-tools/Authentication/LocalSettings.cs, src/dotnet-roslyn-tools/Authentication/PopUps/AuthenticateEditorPopUp.cs, src/dotnet-roslyn-tools/Authentication/PopUps/EditorPopUp.cs, src/dotnet-roslyn-tools/Authentication/PopUps/LocalHelpers.cs, src/dotnet-roslyn-tools/Authentication/PopUps/UxManager.cs, src/dotnet-roslyn-tools/Authentication/RoslynToolsSettings.cs, src/dotnet-roslyn-tools/Commands/AuthenticateCommand.cs, src/dotnet-roslyn-tools/Commands/CommonOptions.cs, src/dotnet-roslyn-tools/Commands/CreateReleaseTagsCommand.cs, src/dotnet-roslyn-tools/Commands/RootRoslynCommand.cs, src/dotnet-roslyn-tools/Commands/VSBranchInfoCommand.cs, src/dotnet-roslyn-tools/CreateReleaseTags/CreateReleaseTags.cs, src/dotnet-roslyn-tools/Utilities/AzDOConnection.cs, src/dotnet-roslyn-tools/VS/VSBranchInfo.cs, src/dotnet-roslyn-tools/readme.md
=> Add authenticate subcommand for entering PATs

src/dotnet-roslyn-tools/CreateReleaseTags/CreateReleaseTags.cs, src/dotnet-roslyn-tools/Products/IProduct.cs, src/dotnet-roslyn-tools/Products/Razor.cs, src/dotnet-roslyn-tools/Products/Roslyn.cs, src/dotnet-roslyn-tools/Products/TypeScript.cs, src/dotnet-roslyn-tools/VS/VSBranchInfo.cs
Adding another partner team to the list...
=> Add TypeScript Tools to vsbranchinfo

src/RoslynInsertionTool/RoslynInsertionTool/VersionsUpdater.cs
test - https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/397676?_a=files
=> Make assembly versions update more resilient to random new lines

src/GitHubCreateMergePRs/config.xml
Also want to try this strategy out over at least a week and see if there are any gains: https://github.com/dotnet/roslyn/compare/features/cache-artifacts?expand=1
=> auto merge features/cache-artifacts

src/GitHubCreateMergePRs/config.xml
=> Update merge PR owner to new Tiger

eng/Versions.props
Resolves governance issue https://devdiv.visualstudio.com/devdiv/_componentGovernance/112189/alert/7082173?typeId=6258469 (microsoft)
=> Update Newtonsoft.Json to 13.0.1

src/GitHubCreateMergePRs/config.xml
=> Remove -vs-deps branches from flow after merge

src/RoslynInsertionTool/README.md, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/App.config, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.Designer.cs, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.settings, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/scripts/HelperFunctions.ps1
=> Make dn-bot the default user for insertions.

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/App.config, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/RoslynInsertionToolCommandline.cs, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.Designer.cs, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.settings, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs, src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionToolOptions.cs, src/RoslynInsertionTool/scripts/HelperFunctions.ps1, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1
Example - https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/424047
This option will be set in PR validation builds (since we don't have too many of those).
=> Add option to allow one off insertions to queue speedometer runs

src/GitHubCreateMergePRs/config.xml
=> Flow project system 17.4.x branch to main.

src/GitHubCreateMergePRs/config.xml
=> Add back -vs-deps to `config.xml`

src/GitHubCreateMergePRs/config.xml
=> Remove lambda feature branch from merge bot

src/GitHubCreateMergePRs/config.xml
Release/dev17.6 is nolonger needed
=> Remove release dev17.6

src/dotnet-roslyn-tools/Commands/CreateReleaseTagsCommand.cs, src/dotnet-roslyn-tools/Commands/VSBranchInfoCommand.cs, src/dotnet-roslyn-tools/CreateReleaseTags/BuildInformation.cs, src/dotnet-roslyn-tools/CreateReleaseTags/CreateReleaseTags.cs, src/dotnet-roslyn-tools/Products/FSharp.cs, src/dotnet-roslyn-tools/Products/IProduct.cs, src/dotnet-roslyn-tools/Products/Razor.cs, src/dotnet-roslyn-tools/Products/Roslyn.cs, src/dotnet-roslyn-tools/Products/TypeScript.cs
Hopefully this won't break anything 🤷‍♂️
=> Allow create-release-tags to work for Razor

src/GitHubCreateMergePRs/config.xml
=> Fix razor merge config

src/GitHubCreateMergePRs/config.xml
@allisonchou 
Yeah. I forgot to do this for myself. So now I'm sending this, to mark it as the end of my tiger-ing stint, for now :P
=> Handoff tiger

src/GitHubCreateMergePRs/config.xml
Thanks @Cosifne for the catch!
=> -vs-deps updates

src/GitHubCreateMergePRs/config.xml
I Keeps forget to chagne this. And all the code flow PRs are assigned to David
=> Change owner of the code flow PR

src/GitHubCreateMergePRs/config.xml
Add newly created `release/7.0.4xx` branch for `roslyn-analyzers` repo
=> Update config.xml add release/7.0.4xx branch for roslyn-analyzers repo

src/ProjectDependencies/DependencyNode.cs, src/ProjectDependencies/MainWindow.xaml, src/ProjectDependencies/MainWindow.xaml.cs
=> Fix rendering of DependencyNode

src/GitHubCreateMergePRs/config.xml
Add 6.0.1xx branch and remove 6.0.2xx
=> Update dotnet format codeflow

src/GitHubCreateMergePRs/config.xml
=> Change mergeOwners to dibarbet

src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.csproj
=> Update System.ValueTuple to 4.5.0

src/GitHubCreateMergePRs/config.xml
These feature branches do not appear to be used.  Removing.
=> Remove stale feature branches

src/RoslynInsertionTool/RoslynInsertionTool.Commandline/App.config, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.Designer.cs, src/RoslynInsertionTool/RoslynInsertionTool.Commandline/Settings.settings
Issuer is fixed in [this PR](https://devdiv.visualstudio.com/DevDiv/_git/a290117c-5a8a-40f7-bc2c-f14dbe3acf6d/pullrequest/558810)
=> Don't update XAML version

src/GitHubCreateMergePRs/config.xml
Moved to using https://github.com/dotnet/arcade/blob/main/Documentation/Maestro/New-Inter-Branch-Merge-Approach.md
=> Remove the GH merge config for vscode-csharp repo.

eng/Signing.props, src/dotnet-roslyn-tools/.vscode/launch.json, src/dotnet-roslyn-tools/Authentication/LocalSettings.cs, src/dotnet-roslyn-tools/Authentication/PopUps/AuthenticateEditorPopUp.cs, src/dotnet-roslyn-tools/Authentication/RoslynToolsSettings.cs, src/dotnet-roslyn-tools/Commands/CommonOptions.cs, src/dotnet-roslyn-tools/Commands/CreateReleaseTagsCommand.cs, src/dotnet-roslyn-tools/Commands/PRTaggerCommand.cs, src/dotnet-roslyn-tools/Commands/VSBranchInfoCommand.cs, src/dotnet-roslyn-tools/CreateReleaseTags/CreateReleaseTags.cs, src/dotnet-roslyn-tools/Logging/SimpleConsoleLogger.cs, src/dotnet-roslyn-tools/Microsoft.RoslynTools.csproj, src/dotnet-roslyn-tools/PRFinder/Formatters/ChangelogFormatter.cs, src/dotnet-roslyn-tools/PRTagger/PRTagger.cs, src/dotnet-roslyn-tools/PRTagger/RemoteConnections.cs, src/dotnet-roslyn-tools/Utilities/AzDOConnection.cs, src/dotnet-roslyn-tools/VS/VSBranchInfo.cs
- Uses DarcLib to provide interactive authentication.
Tokens can still be saved to your local settings or provided through the command line options.
=> Adds interactive authentication for Azure DevOps connections.

src/GitHubCreateMergePRs/config.xml
=> Remove merge from 17.6 to 17.8 and 17.8 to 17.10

src/RoslynInsertionTool/scripts/HelperFunctions.ps1, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1
https://github.com/dotnet/roslyn/blob/8903f4b17a8dabe5cba91a9d37ee458a466476ab/eng/pipelines/insert.yml#L214
Parameter is passed as string, not switch
=> Change from switch to string

src/RoslynInsertionTool/scripts/HelperFunctions.ps1, src/RoslynInsertionTool/scripts/OneOffInsertion.ps1
For the changes in https://github.com/dotnet/roslyn/pull/75552 to work, we need to add a matching parameter to the RIT scripts.
=> Add parameter to RIT scripts for RetainInsertedBuild

src/GitHubCreateMergePRs/config.xml
Remove some inter-branch merges for Razor, to match Roslyn's inter-branch merges
=> Remove some inter-branch merges for Razor

src/GitHubCreateMergePRs/config.xml
We are switching to a manual backporting model
=> Disable Roslyn forward code flow

src/GitHubCreateMergePRs/config.xml
https://github.com/dotnet/templates has been archived.
https://github.com/dotnet/msbuild-language-service has been archived.
=> Remove dotnet/templates & dotnet/msbuild-language-service codeflow

src/GitHubCreateMergePRs/config.xml
F# moved to Arcade inter-merge GH action in https://github.com/dotnet/fsharp/pull/18267
=> Remove F# codeflow config

src/dotnet-roslyn-tools/Commands/PRFinderCommand.cs, src/dotnet-roslyn-tools/PRFinder/Hosts/Azure.cs, src/dotnet-roslyn-tools/PRFinder/Hosts/GitHub.cs, src/dotnet-roslyn-tools/PRFinder/IRepositoryHost.cs, src/dotnet-roslyn-tools/PRFinder/PRFinder.cs, src/dotnet-roslyn-tools/PRTagger/PRTagger.cs, src/dotnet-roslyn-tools/Utilities/RemoteConnections.cs
Builds on refactoring PR https://github.com/dotnet/roslyn-tools/pull/1475
Filter found PRs by whether they have a specific label.
=> Add `--label` option for filtering the pr-finder command.
